const Permissions = {
  ASSESS_ACCESS: 'ASSESS_ACCESS',
  ASSESS_CREATE: 'ASSESS_CREATE',
  ASSESS_UPDATE: 'ASSESS_UPDATE',
  ASSESS_DELETE: 'ASSESS_DELETE',

  ANALYZE_ACCESS: 'ANALYZE_ACCESS',
  ANALYZE_CREATE: 'ANALYZE_CREATE',
  ANALYZE_UPDATE: 'ANALYZE_UPDATE',
  ANALYZE_DELETE: 'ANALYZE_DELETE',

  PUBLISH_ACCESS: 'PUBLISH_ACCESS',
  PUBLISH_CREATE: 'PUBLISH_CREATE',
  PUBLISH_UPDATE: 'PUBLISH_UPDATE',
  PUBLISH_DELETE: 'PUBLISH_DELETE',
  PUBLISH_PRODUCT: 'PUBLISH_PRODUCT',

  MY_ASSETS_ACCESS: 'MY_ASSETS_ACCESS',
  MY_ASSETS_CREATE: 'MY_ASSETS_CREATE',
  MY_ASSETS_CONFIG: 'MY_ASSETS_CONFIG',

  CONFIG_ACCESS: 'CONFIG_ACCESS',

  CONFIG_ORGANIZATION_ACCESS: 'CONFIG_ORGANIZATION_ACCESS',
  CONFIG_ORGANIZATION_CREATE: 'CONFIG_ORGANIZATION_CREATE',
  CONFIG_ORGANIZATION_UPDATE: 'CONFIG_ORGANIZATION_UPDATE',
  CONFIG_ORGANIZATION_DELETE: 'CONFIG_ORGANIZATION_DELETE',

  CONFIG_USER_ACCESS: 'CONFIG_USER_ACCESS',
  CONFIG_USER_CREATE: 'CONFIG_USER_CREATE',
  CONFIG_USER_UPDATE: 'CONFIG_USER_UPDATE',
  CONFIG_USER_DELETE: 'CONFIG_USER_DELETE',

  CONFIG_ROLE_ACCESS: 'CONFIG_ROLE_ACCESS',
  CONFIG_ROLE_CREATE: 'CONFIG_ROLE_CREATE',
  CONFIG_ROLE_UPDATE: 'CONFIG_ROLE_UPDATE',
  CONFIG_ROLE_DELETE: 'CONFIG_ROLE_DELETE',

  CONFIG_ACL_ACCESS: 'CONFIG_ACL_ACCESS',
  CONFIG_ACL_CREATE: 'CONFIG_ACL_CREATE',
  CONFIG_ACL_UPDATE: 'CONFIG_ACL_UPDATE',
  CONFIG_ACL_DELETE: 'CONFIG_ACL_DELETE',

  CONFIG_ATTRIBUTE_ACCESS: 'CONFIG_ATTRIBUTE_ACCESS',
  CONFIG_ATTRIBUTE_CREATE: 'CONFIG_ATTRIBUTE_CREATE',
  CONFIG_ATTRIBUTE_UPDATE: 'CONFIG_ATTRIBUTE_UPDATE',
  CONFIG_ATTRIBUTE_DELETE: 'CONFIG_ATTRIBUTE_DELETE',

  CONFIG_REPORT_TYPE_ACCESS: 'CONFIG_REPORT_TYPE_ACCESS',
  CONFIG_REPORT_TYPE_CREATE: 'CONFIG_REPORT_TYPE_CREATE',
  CONFIG_REPORT_TYPE_UPDATE: 'CONFIG_REPORT_TYPE_UPDATE',
  CONFIG_REPORT_TYPE_DELETE: 'CONFIG_REPORT_TYPE_DELETE',

  CONFIG_WORD_LIST_ACCESS: 'CONFIG_WORD_LIST_ACCESS',
  CONFIG_WORD_LIST_CREATE: 'CONFIG_WORD_LIST_CREATE',
  CONFIG_WORD_LIST_UPDATE: 'CONFIG_WORD_LIST_UPDATE',
  CONFIG_WORD_LIST_DELETE: 'CONFIG_WORD_LIST_DELETE',

  CONFIG_BOT_ACCESS: 'CONFIG_BOT_ACCESS',
  CONFIG_BOT_CREATE: 'CONFIG_BOT_CREATE',
  CONFIG_BOT_UPDATE: 'CONFIG_BOT_UPDATE',
  CONFIG_BOT_DELETE: 'CONFIG_BOT_DELETE',

  CONFIG_OSINT_SOURCE_ACCESS: 'CONFIG_OSINT_SOURCE_ACCESS',
  CONFIG_OSINT_SOURCE_CREATE: 'CONFIG_OSINT_SOURCE_CREATE',
  CONFIG_OSINT_SOURCE_UPDATE: 'CONFIG_OSINT_SOURCE_UPDATE',
  CONFIG_OSINT_SOURCE_DELETE: 'CONFIG_OSINT_SOURCE_DELETE',

  CONFIG_OSINT_SOURCE_GROUP_ACCESS: 'CONFIG_OSINT_SOURCE_GROUP_ACCESS',
  CONFIG_OSINT_SOURCE_GROUP_CREATE: 'CONFIG_OSINT_SOURCE_GROUP_CREATE',
  CONFIG_OSINT_SOURCE_GROUP_UPDATE: 'CONFIG_OSINT_SOURCE_GROUP_UPDATE',
  CONFIG_OSINT_SOURCE_GROUP_DELETE: 'CONFIG_OSINT_SOURCE_GROUP_DELETE',

  CONFIG_PRODUCT_TYPE_ACCESS: 'CONFIG_PRODUCT_TYPE_ACCESS',
  CONFIG_PRODUCT_TYPE_CREATE: 'CONFIG_PRODUCT_TYPE_CREATE',
  CONFIG_PRODUCT_TYPE_UPDATE: 'CONFIG_PRODUCT_TYPE_UPDATE',
  CONFIG_PRODUCT_TYPE_DELETE: 'CONFIG_PRODUCT_TYPE_DELETE',

  CONFIG_PUBLISHER_PRESET_ACCESS: 'CONFIG_PUBLISHER_PRESET_ACCESS',
  CONFIG_PUBLISHER_PRESET_CREATE: 'CONFIG_PUBLISHER_PRESET_CREATE',
  CONFIG_PUBLISHER_PRESET_UPDATE: 'CONFIG_PUBLISHER_PRESET_UPDATE',
  CONFIG_PUBLISHER_PRESET_DELETE: 'CONFIG_PUBLISHER_PRESET_DELETE',

  CONFIG_WORKER_ACCESS: 'CONFIG_WORKER_ACCESS',
  CONFIG_API_ACCESS: 'CONFIG_API_ACCESS'
}

export default Permissions
