apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core
  labels:
    {{- include "taranis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.core.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.core.size }}
  storageClassName: {{ .Values.storage.core.storageClassName | quote }}
