apiVersion: v1
kind: Secret
metadata:
  name: taranis-secrets
  labels:
    {{- include "taranis.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
  BOT_API_KEY: {{ .Values.secrets.botApiKey | quote }}
  PRE_SEED_PASSWORD_ADMIN: {{ .Values.secrets.preSeedPasswordAdmin | quote }}
  PRE_SEED_PASSWORD_USER: {{ .Values.secrets.preSeedPasswordUser | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    {{- include "taranis.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.database.host | quote }}
  DB_DATABASE: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: taranis-rabbitmq-credentials
  labels:
    {{- include "taranis.labels" . | nindent 4 }}
type: Opaque
stringData:
  QUEUE_BROKER_HOST: {{ .Values.rabbitmq.host | quote }}
  QUEUE_BROKER_USER: {{ .Values.rabbitmq.user | quote }}
  QUEUE_BROKER_PASSWORD: {{ .Values.rabbitmq.password | quote }}
