source = {
    "description": "",
    "icon": None,
    "id": "b583f4ae-7ec3-492a-a36d-ed9cfc0b4a28",
    "last_attempted": None,
    "last_collected": None,
    "last_error_message": None,
    "name": "https",
    "parameters": {
        "ADDITIONAL_HEADERS": "",
        "API_KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "PROXY_SERVER": "",
        "REFRESH_INTERVAL": "",
        "URL": "https://test.misp.test",
        "USER_AGENT": "",
        "SHARING_GROUP_ID": "1",
        "ORGANISATION_ID": "1",
    },
    "state": -1,
    "type": "misp_connector",
}
misp_event = {
    "Event": {
        "id": "49",
        "orgc_id": "1",
        "org_id": "1",
        "date": "2025-05-06",
        "threat_level_id": "4",
        "info": "test",
        "published": False,
        "uuid": "a5fd9136-59ee-4178-8139-742130ed50a7",
        "attribute_count": "22",
        "analysis": "0",
        "timestamp": "1746566432",
        "distribution": "4",
        "proposal_email_lock": False,
        "locked": False,
        "publish_timestamp": "0",
        "sharing_group_id": "1",
        "disable_correlation": False,
        "extends_uuid": "",
        "protected": None,
        "event_creator_email": "test_user@misp.test",
        "Org": {
            "id": "1",
            "name": "TEST",
            "uuid": "f05f0c5a-4139-4f42-b3b5-5351e582f26f",
            "local": True,
        },
        "Orgc": {
            "id": "1",
            "name": "TEST",
            "uuid": "f05f0c5a-4139-4f42-b3b5-5351e582f26f",
            "local": True,
        },
        "SharingGroup": {
            "id": "1",
            "name": "sharing group 1",
            "releasability": "",
            "description": "",
            "uuid": "5eff141b-a2ad-422e-bd03-86d63d6fccc6",
            "organisation_uuid": "f05f0c5a-4139-4f42-b3b5-5351e582f26f",
            "org_id": "1",
            "sync_user_id": "0",
            "active": True,
            "created": "2025-04-30 14:29:45",
            "modified": "2025-04-30 14:29:45",
            "local": True,
            "roaming": False,
            "Organisation": {
                "id": "1",
                "name": "TEST",
                "uuid": "f05f0c5a-4139-4f42-b3b5-5351e582f26f",
            },
            "SharingGroupOrg": [
                {
                    "id": "1",
                    "sharing_group_id": "1",
                    "org_id": "1",
                    "extend": True,
                    "Organisation": {
                        "id": "1",
                        "name": "TEST",
                        "uuid": "f05f0c5a-4139-4f42-b3b5-5351e582f26f",
                    },
                }
            ],
            "SharingGroupServer": [
                {
                    "id": "1",
                    "sharing_group_id": "1",
                    "server_id": "0",
                    "all_orgs": False,
                    "Server": {
                        "id": "0",
                        "url": "https://test.misp.test",
                        "name": "https://test.misp.test",
                    },
                }
            ],
        },
        "Attribute": [],
        "ShadowAttribute": [],
        "RelatedEvent": [
            {
                "Event": {
                    "id": "51",
                    "date": "2025-05-07",
                    "threat_level_id": "4",
                    "info": "Related event",
                    "published": False,
                    "uuid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                    "analysis": "0",
                    "timestamp": "1746596697",
                    "distribution": "1",
                    "org_id": "1",
                    "orgc_id": "1",
                    "Org": {
                        "id": "1",
                        "name": "TEST",
                        "uuid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                    },
                    "Orgc": {
                        "id": "1",
                        "name": "TEST",
                        "uuid": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                    },
                },
                "RelationshipInbound": [],
            },
        ],
        "Galaxy": [],
        "Object": [
            {
                "id": "278",
                "name": "taranis-news-item",
                "meta-category": "misc",
                "description": "An object describing a news item from Taranis AI",
                "template_uuid": "e4b7e5e3-2c4c-4edf-b9a3-2c2a32844e62",
                "template_version": "2",
                "event_id": "49",
                "uuid": "61ef2312-4204-4f11-a475-5340a17ed12a",
                "timestamp": "1746566432",
                "distribution": "5",
                "sharing_group_id": "0",
                "comment": "",
                "deleted": False,
                "first_seen": None,
                "last_seen": None,
                "ObjectReference": [],
                "Attribute": [
                    {
                        "id": "9615",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "edee538c-6977-47e0-8663-5732102b9524",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "title",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "test",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9616",
                        "type": "datetime",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "f3cba616-77e0-4f5f-a821-41d90473a83d",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "published",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "2025-05-04T21:30:39.055000+0200",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9617",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "543dac9a-bcf1-4775-8b5c-0602cb4bd894",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "author",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "Arthur Dent",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9618",
                        "type": "datetime",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "eb68273a-e618-41f2-8bbe-932d9f476d43",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "collected",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "2025-05-04T21:30:43.619000+0200",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9619",
                        "type": "sha256",
                        "category": "Payload delivery",
                        "to_ids": True,
                        "uuid": "a750f3b9-2a7a-4fc4-b60b-b00003bbdbb8",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "hash",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9620",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "031303ec-822c-4e86-aa6a-930a07cfa105",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "id",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "71e99643-c92b-48a6-a316-f73dbab00a2e",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9621",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "5c20006e-ece8-494d-96fe-070685fcc86e",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "osint_source_id",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "manual",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9622",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "8e01d062-abc5-456c-9054-1564cd0407a9",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "review",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "test",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9623",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "9c3e2344-b09c-407d-a584-d2c292192c63",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "278",
                        "object_relation": "story_id",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "a5fd9136-59ee-4178-8139-742130ed50a7",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                ],
            },
            {
                "id": "279",
                "name": "taranis-story",
                "meta-category": "misc",
                "description": "An object describing a story item from Taranis or similar source",
                "template_uuid": "a2716df6-920b-4c4e-85f7-79a009476f3d",
                "template_version": "1",
                "event_id": "49",
                "uuid": "27265e84-4251-48f6-9f66-4975d9104407",
                "timestamp": "1746566432",
                "distribution": "5",
                "sharing_group_id": "0",
                "comment": "",
                "deleted": False,
                "first_seen": None,
                "last_seen": None,
                "ObjectReference": [],
                "Attribute": [
                    {
                        "id": "9624",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "2bf895d3-d709-4d35-9c50-3a484409db91",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "comments",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "sdaf\nsdaf",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9625",
                        "type": "datetime",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "95018146-edf9-4cd8-995a-7556c5733bee",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "created",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "2025-05-04T21:30:39.055000+0200",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9626",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "14688211-35e1-4480-8eb7-1d4c04743afb",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "description",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "test",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9627",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "56bd9c79-3125-4f23-8191-3c8b9c3dcc21",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "dislikes",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "0",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9628",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "b5917a74-4483-445b-a13b-2e28ce26bd88",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "id",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "a5fd9136-59ee-4178-8139-742130ed50a7",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9629",
                        "type": "boolean",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "37cf1cc1-b338-40aa-bb59-db976280525f",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "important",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "0",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9630",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "11cc3f7b-8fad-4010-9e0f-db46dd984e0b",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "likes",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "0",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9631",
                        "type": "boolean",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "baff180f-9717-4d08-a8c7-8df3a4e2f8fa",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "read",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "0",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9632",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "4d88c2ea-cd11-459f-8d98-f91562352db4",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "relevance",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "0",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9633",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "19a6e75e-ac19-4399-a3e9-d98e7286cfa2",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "title",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "test",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9634",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "0d9e865f-17af-4866-8307-50644b0d3183",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "attributes",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "{'key': 'TLP', 'value': 'clear'}",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9635",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "f90ed4a9-a5d8-438d-af55-fbaaaa49f77c",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "attributes",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "{'key': 'cybersecurity', 'value': 'none'}",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                    {
                        "id": "9636",
                        "type": "text",
                        "category": "Other",
                        "to_ids": False,
                        "uuid": "c9a9d111-c718-475e-ba0d-ced8ce5a4c9a",
                        "event_id": "49",
                        "distribution": "5",
                        "timestamp": "1746566432",
                        "comment": "",
                        "sharing_group_id": "0",
                        "deleted": False,
                        "disable_correlation": False,
                        "object_id": "279",
                        "object_relation": "attributes",
                        "first_seen": None,
                        "last_seen": None,
                        "value": "{'key': 'misp_event_uuid', 'value': 'a5fd9136-59ee-4178-8139-742130ed50a7'}",
                        "Galaxy": [],
                        "ShadowAttribute": [],
                    },
                ],
            },
        ],
        "EventReport": [
            {
                "id": "38",
                "uuid": "bb1d81fb-4063-427c-a601-537d6547f78f",
                "event_id": "49",
                "name": "test",
                "content": "# Story description\ntest\n\n# Story comment\nTEST\nTEST",
                "distribution": "5",
                "sharing_group_id": "0",
                "timestamp": "1746566432",
                "deleted": False,
            }
        ],
        "CryptographicKey": [],
    }
}

taranis_objects = [
    {
        "Object": {
            "id": "278",
            "name": "taranis-news-item",
            "meta-category": "misc",
            "description": "An object describing a news item from Taranis AI",
            "template_uuid": "e4b7e5e3-2c4c-4edf-b9a3-2c2a32844e62",
            "template_version": "2",
            "event_id": "49",
            "uuid": "61ef2312-4204-4f11-a475-5340a17ed12a",
            "timestamp": "1746566432",
            "distribution": "5",
            "sharing_group_id": "0",
            "comment": "",
            "deleted": False,
            "first_seen": None,
            "last_seen": None,
            "Attribute": [
                {
                    "id": "9615",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "title",
                    "category": "Other",
                    "type": "text",
                    "value1": "test",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "edee538c-6977-47e0-8663-5732102b9524",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "test",
                    "AttributeTag": [],
                },
                {
                    "id": "9616",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "published",
                    "category": "Other",
                    "type": "datetime",
                    "value1": "2025-05-04T21:30:39.055000+0200",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "f3cba616-77e0-4f5f-a821-41d90473a83d",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "2025-05-04T21:30:39.055000+0200",
                    "AttributeTag": [],
                },
                {
                    "id": "9617",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "author",
                    "category": "Other",
                    "type": "text",
                    "value1": "Arthur Dent",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "543dac9a-bcf1-4775-8b5c-0602cb4bd894",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "Arthur Dent",
                    "AttributeTag": [],
                },
                {
                    "id": "9618",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "collected",
                    "category": "Other",
                    "type": "datetime",
                    "value1": "2025-05-04T21:30:43.619000+0200",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "eb68273a-e618-41f2-8bbe-932d9f476d43",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "2025-05-04T21:30:43.619000+0200",
                    "AttributeTag": [],
                },
                {
                    "id": "9619",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "hash",
                    "category": "Payload delivery",
                    "type": "sha256",
                    "value1": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                    "value2": "",
                    "to_ids": True,
                    "uuid": "a750f3b9-2a7a-4fc4-b60b-b00003bbdbb8",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
                    "AttributeTag": [],
                },
                {
                    "id": "9620",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "id",
                    "category": "Other",
                    "type": "text",
                    "value1": "71e99643-c92b-48a6-a316-f73dbab00a2e",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "031303ec-822c-4e86-aa6a-930a07cfa105",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "71e99643-c92b-48a6-a316-f73dbab00a2e",
                    "AttributeTag": [],
                },
                {
                    "id": "9621",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "osint_source_id",
                    "category": "Other",
                    "type": "text",
                    "value1": "manual",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "5c20006e-ece8-494d-96fe-070685fcc86e",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "manual",
                    "AttributeTag": [],
                },
                {
                    "id": "9622",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "review",
                    "category": "Other",
                    "type": "text",
                    "value1": "test",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "8e01d062-abc5-456c-9054-1564cd0407a9",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "test",
                    "AttributeTag": [],
                },
                {
                    "id": "9623",
                    "event_id": "49",
                    "object_id": "278",
                    "object_relation": "story_id",
                    "category": "Other",
                    "type": "text",
                    "value1": "a5fd9136-59ee-4178-8139-742130ed50a7",
                    "value2": "",
                    "to_ids": False,
                    "uuid": "9c3e2344-b09c-407d-a584-d2c292192c63",
                    "timestamp": "1746566432",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "disable_correlation": False,
                    "first_seen": None,
                    "last_seen": None,
                    "value": "a5fd9136-59ee-4178-8139-742130ed50a7",
                    "AttributeTag": [],
                },
            ],
            "Event": {"id": "49", "info": "test", "org_id": "1", "orgc_id": "1"},
        }
    },
]
