source = {
    "description": "",
    "icon": None,
    "id": "b583f4ae-7ec3-492a-a36d-ed9cfc0b4a28",
    "last_attempted": None,
    "last_collected": None,
    "last_error_message": None,
    "name": "https",
    "parameters": {
        "ADDITIONAL_HEADERS": "",
        "API_KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "PROXY_SERVER": "",
        "REFRESH_INTERVAL": "",
        "URL": "https://test.misp.test",
        "USER_AGENT": "",
        "SHARING_GROUP_ID": "1",
        "ORGANISATION_ID": "1",
    },
    "state": -1,
    "type": "misp_connector",
}

taranis_events = [
    {
        "Event": {
            "id": "170",
            "orgc_id": "2",
            "org_id": "2",
            "date": "2025-10-15",
            "threat_level_id": "4",
            "info": "Rat der Innenminister in Luxemburg: Karner fordert Abschiebungen nach Syrien aus ganz Europa",
            "published": False,
            "uuid": "320d4589-cd71-4722-aa28-ea5530e99830",
            "attribute_count": "39",
            "analysis": "0",
            "timestamp": "1762188357",
            "distribution": "4",
            "proposal_email_lock": True,
            "locked": False,
            "publish_timestamp": "0",
            "first_publication": "0",
            "sharing_group_id": "1",
            "disable_correlation": False,
            "extends_uuid": "",
            "protected": None,
            "event_creator_email": "org-1@user.ai",
            "Org": {"id": "2", "name": "org-1", "uuid": "c0458300-2f8a-499e-8413-f4a6f5fc46c5", "local": True},
            "Orgc": {"id": "2", "name": "org-1", "uuid": "c0458300-2f8a-499e-8413-f4a6f5fc46c5", "local": True},
            "SharingGroup": {
                "id": "1",
                "name": "internal evaluation sharing group",
                "releasability": "",
                "description": "",
                "uuid": "b1c6ea61-dbe8-40ce-a16e-f246d571fb3c",
                "organisation_uuid": "21f5b85d-bddc-470b-ac47-04d3214e7206",
                "org_id": "1",
                "sync_user_id": "0",
                "active": True,
                "created": "2025-04-28 23:47:28",
                "modified": "2025-07-16 08:49:26",
                "local": True,
                "roaming": False,
                "Organisation": {"id": "1", "name": "ADMIN", "uuid": "21f5b85d-bddc-470b-ac47-04d3214e7206"},
                "SharingGroupOrg": [],
                "SharingGroupServer": [],
            },
            "Attribute": [],
            "ShadowAttribute": [],
            "RelatedEvent": [
                {
                    "Event": {
                        "id": "167",
                        "date": "2025-09-30",
                        "threat_level_id": "4",
                        "info": 'Oktober im Zeichen von "Coffee with Cops"',
                        "published": False,
                        "uuid": "a2309540-be46-481f-8247-e9af20911986",
                        "analysis": "0",
                        "timestamp": "1759191627",
                        "distribution": "4",
                        "org_id": "2",
                        "orgc_id": "2",
                        "Org": {"id": "2", "name": "org-1", "uuid": "c0458300-2f8a-499e-8413-f4a6f5fc46c5"},
                        "Orgc": {"id": "2", "name": "org-1", "uuid": "c0458300-2f8a-499e-8413-f4a6f5fc46c5"},
                    }
                },
                {
                    "Event": {
                        "id": "168",
                        "date": "2025-09-30",
                        "threat_level_id": "4",
                        "info": "Arbeitsgespräch zur Umsetzung des Europäischen Asyl- und Migrationspakts",
                        "published": False,
                        "uuid": "badb1546-c774-4183-a2d5-6267fec27b5f",
                        "analysis": "0",
                        "timestamp": "1759309360",
                        "distribution": "4",
                        "org_id": "2",
                        "orgc_id": "2",
                        "Org": {"id": "2", "name": "org-1", "uuid": "c0458300-2f8a-499e-8413-f4a6f5fc46c5"},
                        "Orgc": {"id": "2", "name": "org-1", "uuid": "c0458300-2f8a-499e-8413-f4a6f5fc46c5"},
                    }
                },
            ],
            "Galaxy": [],
            "Object": [
                {
                    "id": "763",
                    "name": "taranis-news-item",
                    "meta-category": "misc",
                    "description": "An object describing a news item from Taranis AI",
                    "template_uuid": "e4b7e5e3-2c4c-4edf-b9a3-2c2a32844e62",
                    "template_version": "2",
                    "event_id": "170",
                    "uuid": "cd4725e6-99b5-44cb-87cc-2c8b759df377",
                    "timestamp": "1760568797",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "first_seen": None,
                    "last_seen": None,
                    "ObjectReference": [],
                    "Attribute": [
                        {
                            "id": "17210",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "8fa85b2d-c232-44f7-b864-d7c49c4cd88a",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "title",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "Kompetenzzentrum Sicheres Österreich ist wichtiger Faktor für Sicherheit in Österreich",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17211",
                            "type": "link",
                            "category": "External analysis",
                            "to_ids": False,
                            "uuid": "ec47807c-bc32-41b1-b4e6-d2fe9800c284",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "link",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "https://www.bmi.gv.at/news.aspx?id=53546B674559447350694D3D",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17212",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "e0327a5f-53c8-4268-ac1c-df8b5e25a0ce",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "content",
                            "first_seen": None,
                            "last_seen": None,
                            "value": 'Aktuelles\nKompetenzzentrum Sicheres Österreich ist wichtiger Faktor für Sicherheit in Österreich\nDas Kompetenzzentrum Sicheres Österreich (KSÖ) feiert heuer sein 50-jähriges Bestehen und lud am 13. Oktober 2025 zur Jubiläumsveranstaltung im Raiffeisen Forum ein.\nKSÖ-Präsident Michael Höllerer, Generaldirektor der Raiffeisenlandesbank Niederösterreich und Wien, eröffnete die Veranstaltung. Danach zog Innenminister Gerhard Karner in seiner Festrede einen Vergleich zwischen den sicherheitspolitischen Herausforderungen von vor 50 Jahren zu jenen von heute.\n"Vor 50 Jahren gab es genauso wie auch heute Herausforderungen im Bereich der Sicherheit, aber die Art der Kriminalität hat sich verändert. Von Banküberfällen hin zu Cyberangriffen, von kriminellen Gruppierungen hin zu radikalisierten Einzeltätern. Umso wichtiger ist ein enger Schulterschluss der Sicherheitsbehörden und der Wirtschaft. Es braucht ein Bollwerk für die Sicherheit in unserem Land. Dabei wird das Kompetenzzentrum Sicheres Österreich – genauso wie in den vergangenen 50 Jahren – eine ganz wesentliche Rolle spielen, davon bin ich überzeugt", sagte Innenminister Gerhard Karner.\nNach einer Filmvorführung "50 Jahre KSÖ" diskutierten Innenminister Gerhard Karner und Innenminister außer Dienst, Karl Schlögl, über die "Sicherheitspolitik im Wandel der Zeit". Eine Keynote von Kriminal- und Geheimdienstanalyst Marc Torben Hofmann zum Thema "Der Faktor Mensch" und ein Ausblick von KSÖ-Generalsekretär Alexander Janda rundeten das Programm ab.\nÖsterreich damals wie heute eines der sichersten Länder der Welt\n"Eines steht fest: Österreich war damals und ist auch heute eines der sichersten Länder der Welt", betonte Innenminister Gerhard Karner in seiner Festrede. Dennoch habe sich die Sicherheitslage in den vergangenen Jahren spürbar verändert – sowohl in der Art der Kriminalität als auch in der Art, wie über sie berichtet wird.\nSorge vor Anschlägen habe es, so Karner, sowohl früher als auch heute gegeben. Positiv sei jedoch, dass Gewaltdelikte und Einbrüche in den Wohnraum zurückgegangen seien. Auffällig sei hingegen die zunehmende Verlagerung der Kriminalität in den digitalen Raum. Während sich die Menschen früher über Tageszeitungen und Nachrichtensendungen informierten, erhalten sie heute Push-Nachrichten über jede Gewalttat direkt aufs Smartphone. "Das verändert das subjektive Sicherheitsgefühl", erklärte der Innenminister.\nZusammenarbeit und Weiterentwicklung als zentrale Aufgabe\nUm auf diese Entwicklungen angemessen reagieren zu können, brauche es vor allem "enge Zusammenarbeit und ein Bollwerk für die Sicherheit in diesem Land", betonte Karner und verwies auf die aktuellen Herausforderungen in den Bereichen illegale Migration, Cybercrime sowie auf die Chancen und Risiken Künstlicher Intelligenz in der Sicherheitsarbeit.\nEin sichtbares Zeichen dafür sei der KSÖ-Sicherheitspreis, mit dem herausragende Leistungen des Sicherheitsnetzwerks aus Exekutive, Wirtschaft, Wissenschaft und Medien gewürdigt werden.\nKSÖ seit 50 Jahren enger Partner des Innenministeriums\nDas Kompetenzzentrum Sicheres Österreich (KSÖ) wurde 1975 gegründet und engagiert sich seither für Sicherheit, Prävention und gesellschaftliche Verantwortung. Bereits in den Anfangsjahren setzte das KSÖ mit Kampagnen wie "Hände weg von Waffen und Sprengmitteln" sowie Enqueten zu Themen wie Kindeswohl, Versicherungsbetrug und Drogenmissbrauch wichtige Akzente in der öffentlichen Bewusstseinsbildung. Aktuelle Schwerpunkte liegen in den Bereichen Gewaltprävention, Schutz kritischer Infrastrukturen, Deep Fakes, Künstliche Intelligenz und Krisenmanagement.',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17213",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "6cf40798-5bb5-4b47-99ab-a34268c5b9a5",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "author",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "Aktuelles aus dem BMI",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17214",
                            "type": "sha256",
                            "category": "Payload delivery",
                            "to_ids": True,
                            "uuid": "1a1bd59e-4fae-4d37-ac82-1ed90b1c4f89",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "hash",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "446f77f9a65c7d45f31dd813d5da4589541a2cf9013373897910dc84fc148d53",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17215",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "d184352a-4ad2-4307-813f-182deea852a1",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "72cd81f4-5018-487f-a66a-90a04df8df30",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17216",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "b618af02-bdde-45ed-9734-fe4ad47ff18d",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "osint_source_id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "654d35c2-bccc-4a34-bd9a-afc07dc8d86b",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17217",
                            "type": "link",
                            "category": "External analysis",
                            "to_ids": False,
                            "uuid": "bfaa5b8d-fa9e-40e1-9358-8b8f085e9af8",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568797",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "source",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "https://www.bmi.gv.at/rss/bmi_presse.xml",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17218",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "7366516e-4ba8-4e54-80c7-e6f94255b217",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "763",
                            "object_relation": "story_id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "320d4589-cd71-4722-aa28-ea5530e99830",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                    ],
                },
                {
                    "id": "764",
                    "name": "taranis-news-item",
                    "meta-category": "misc",
                    "description": "An object describing a news item from Taranis AI",
                    "template_uuid": "e4b7e5e3-2c4c-4edf-b9a3-2c2a32844e62",
                    "template_version": "2",
                    "event_id": "170",
                    "uuid": "9d5447dc-62d6-4ead-8c8a-1d0b99d4e241",
                    "timestamp": "1760568798",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "first_seen": None,
                    "last_seen": None,
                    "ObjectReference": [],
                    "Attribute": [
                        {
                            "id": "17219",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "c622d06d-4d48-4ffc-8712-ff1741fdd402",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "title",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "Rat der Innenminister in Luxemburg: Karner fordert Abschiebungen nach Syrien aus ganz Europa",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17220",
                            "type": "link",
                            "category": "External analysis",
                            "to_ids": False,
                            "uuid": "ed93a8bb-b4ef-479a-964b-4f941ea31b6c",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "link",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "https://www.bmi.gv.at/news.aspx?id=7979617569673268636B673D",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17221",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "aeb14b2e-523a-41c3-87d8-9d956d651965",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "content",
                            "first_seen": None,
                            "last_seen": None,
                            "value": 'Aktuelles\nRat der Innenminister in Luxemburg: Karner fordert Abschiebungen nach Syrien aus ganz Europa\nDer Rat der Innenminister fand am 14. Oktober 2025 in Luxemburg statt.\nInnenminister Gerhard Karner thematisierte vor allem Abschiebungen nach Syrien aus ganz Europa. Bisher ist Österreich das einzige Land, das Abschiebungen von Syrern in ihr Heimatland durchführte. Das Ziel sei, Abschiebungen nach Syrien auch aus allen anderen europäischen Ländern zu ermöglichen, was eine enge Kooperation und starke Allianzen innerhalb Europas erfordere, betonte Karner.\nVor dem Rat der Innenminister äußerte sich Karner auch zu Rückkehrzentren außerhalb Europas: "Wir werden heute auch über die rechtlichen Notwendigkeiten zur Einrichtung von Rückkehrzentren außerhalb Europas beraten. Dieser Schritt muss rasch gesetzt werden, um das Geschäft der Schleppermafia zu durchkreuzen und damit den Druck auf Europa nachhaltig zu mindern."\nAuch das Thema Asylverfahren in Drittstaaten stand im Fokus der Beratungen. Die Möglichkeit für Asylverfahren in Drittstaaten sei eine wesentliche Voraussetzung, um illegale Migration nach Europa weiter gegen Null zu drängen und dadurch die Verteilung von Asylwerbern in Europa obsolet zu machen, betonte der Innenminister. Österreich sei eines jener Länder, das in den vergangenen zehn Jahren schon einen überdurchschnittlich hohen Beitrag geleistet habe. "Österreich war und wird immer gegen eine Umverteilung sein, weil das in der Praxis schon in der Vergangenheit nicht funktioniert hat."\nIm Rahmen des Innenministertreffens tauschte sich Karner auch mit seinem deutschen Amtskollegen Alexander Dobrindt über Abschiebungen von verurteilten Straftätern nach Syrien und Afghanistan aus.\n"Europa muss härter und noch konsequenter bei der Durchführung von Abschiebungen werden. Das bedeutet auch, Abschiebungen von verurteilten Straftätern und Menschen ohne Bleiberecht in Länder wie Syrien oder Afghanistan durchzuführen. Ich bin davon überzeugt, dass auch andere europäische Länder dem Beispiel Österreichs folgen und verurteilte Straftäter direkt nach Syrien abschieben werden. Österreich hat als erstes und einziges europäisches Land erstmals seit 15 Jahren wieder Abschiebungen direkt nach Syrien durchgeführt und wird die bisherigen Erfahrungen gerne teilen ", hielt Innenminister Gerhard Karner beim Doorstep im Vorfeld des Treffens fest.',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17222",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "55f22694-8c74-41be-a2e9-cdf0a76447e8",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "author",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "Aktuelles aus dem BMI",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17223",
                            "type": "sha256",
                            "category": "Payload delivery",
                            "to_ids": True,
                            "uuid": "58a8d5fa-387d-4b87-9f9e-0fb21d3b68f0",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "hash",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "b1cde3fa4ad7559eeec51cea00524f98255059d871ecb9343f352027458b216e",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17224",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "3a830f5b-1083-4c1e-a703-d265595f4b06",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "c6709e6e-c633-4756-aeb9-b08f98e6c7bc",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17225",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "6c2cfe7b-ff1b-4495-aaa7-99e1909cb21e",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "osint_source_id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "654d35c2-bccc-4a34-bd9a-afc07dc8d86b",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17226",
                            "type": "link",
                            "category": "External analysis",
                            "to_ids": False,
                            "uuid": "d8e012cb-5896-4f20-89b0-abb937de7311",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "source",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "https://www.bmi.gv.at/rss/bmi_presse.xml",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17227",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "befe080a-7a47-465a-a4aa-5988070f4e01",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "764",
                            "object_relation": "story_id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "320d4589-cd71-4722-aa28-ea5530e99830",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                    ],
                },
                {
                    "id": "765",
                    "name": "taranis-news-item",
                    "meta-category": "misc",
                    "description": "An object describing a news item from Taranis AI",
                    "template_uuid": "e4b7e5e3-2c4c-4edf-b9a3-2c2a32844e62",
                    "template_version": "2",
                    "event_id": "170",
                    "uuid": "770579e4-c760-4508-bbcf-12f97ac37397",
                    "timestamp": "1760568798",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "first_seen": None,
                    "last_seen": None,
                    "ObjectReference": [],
                    "Attribute": [
                        {
                            "id": "17228",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "5b33449e-3bf1-42ba-8142-d9c937bc836a",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "title",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "KI-gestützte Förderungskontrolle: Förderabrechnung zukunftsfit gestalten",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17229",
                            "type": "link",
                            "category": "External analysis",
                            "to_ids": False,
                            "uuid": "f727f5ea-08b1-4698-9f9a-cee20ea00b67",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "link",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "https://www.bmi.gv.at/news.aspx?id=74787A31466C4D485032513D",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17230",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "5356a377-90bf-4ab3-9a31-ee1108988eb3",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "content",
                            "first_seen": None,
                            "last_seen": None,
                            "value": 'Aktuelles\nKI-gestützte Förderungskontrolle: Förderabrechnung zukunftsfit gestalten\nDas Bundesministerium für Inneres (BMI) suchte gemeinsam mit der Buchhaltungsagentur des Bundes (BHAG), dem Österreichischen Integrationsfonds (ÖIF), dem Bundesministerium für Kunst, Kultur, öffentlichen Dienst und Sport (BMKÖS) sowie dem Bundeskanzleramt (BKA) im Rahmen der IÖB-Challenge 2024 innovative Ansätze für eine zukunftsfitte Förderungsabrechnung.\nAus diesem Wettbewerb ist das Projekt "KI-gestützte Förderungskontrolle" hervorgegangen, das nun gemeinsam mit dem Gewinner des Wettbewerbs – der Firma Cloudflight – umgesetzt wird.\nDie Herausforderungen und Prozesse der Förderungskontrolle sind in den teilnehmenden Ressorts teilweise IT-gestützt, jedoch nicht durchgehend digitalisiert. Dadurch entstehen hohe manuelle Aufwände und es gibt unzureichende bzw. fehlende digitale Schnittstellen. Ziel des Projekts ist der Aufbau eines ressortübergreifend einsetzbaren und für die gesamte Bundesverwaltung erweiterbaren IT-Verfahrens zur strukturierten Einreichung von Förderungsunterlagen in Kooperation mit dem Sieger der IÖB-Challenge.\nDie Softwarelösung soll Förderungsnehmenden und Förderungsgebenden eine digitale, KI-gestützte Unterstützung im gesamten Prozess der Förderungskontrolle bieten. Im ersten Schritt erhalten förderungsgebende Behörden technische Unterstützung durch automatisierte Vollständigkeits- und Plausibilitätsprüfungen sowie Abgleiche mit rechtlichen und vertraglichen Vorgaben.\nIn der ersten Projektphase erfolgt die Erstellung eines "Proof of Concepts" in Form eines nutzbaren und weiter ausbaubaren "Minimal Viable Products" zur automatisierten Prüfung von Belegen, Rechnungen und Zahlungsnachweisen. Sachbearbeiterinnen und Sachbearbeiter sollen dabei bei der manuellen Prüftätigkeit mit vorgeprüften Datenbeständen entlastet werden.\nDas Projekt leistet einen wichtigen Beitrag zur Umsetzung mehrerer Punkte aus dem Regierungsprogramm:\n• Einsparung in der Verwaltung der Bundesministerien\n• Vermeidung des Missbrauchs von Förderungsmitteln\n• Beitrag zur Evaluierung von Förderungen und zur Vermeidung von Überförderungen\n• Verbesserung des Service des Staates gegenüber Bürgerinnen und Bürgern sowie Unternehmen\n• Einsatz von Large-Language-Models zur Entlastung der Verwaltung und Unterstützung der Bevölkerung',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17231",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "ab9b3067-ff9f-48fe-8a15-476a4819a2d2",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "author",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "Aktuelles aus dem BMI",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17232",
                            "type": "sha256",
                            "category": "Payload delivery",
                            "to_ids": True,
                            "uuid": "46f43902-a365-4a67-9572-e3b8588b1589",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "hash",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "3f9d4113b0d1f3ed4c8082559ba46b674918d760821c59013fa09bccb2b96c54",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17233",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "796905d6-b13f-4f9b-87bc-2bbf2e3d99d9",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "1472eadc-81db-4251-8dff-a9f260d7320a",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17234",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "e151be5a-09ce-4a61-8066-3ba86847452f",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "osint_source_id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "654d35c2-bccc-4a34-bd9a-afc07dc8d86b",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17235",
                            "type": "link",
                            "category": "External analysis",
                            "to_ids": False,
                            "uuid": "3c254729-f093-45c6-ab7a-6072131a2ee4",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "source",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "https://www.bmi.gv.at/rss/bmi_presse.xml",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17236",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "3a45f193-9579-43ef-af96-44b6a8b1c050",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568798",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "765",
                            "object_relation": "story_id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "320d4589-cd71-4722-aa28-ea5530e99830",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                    ],
                },
                {
                    "id": "767",
                    "name": "taranis-story",
                    "meta-category": "misc",
                    "description": "An object describing a story item from Taranis or similar source",
                    "template_uuid": "a2716df6-920b-4c4e-85f7-79a009476f3d",
                    "template_version": "1",
                    "event_id": "170",
                    "uuid": "42d1a0e9-c763-4547-ab8b-221a791840e5",
                    "timestamp": "1760568943",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "comment": "",
                    "deleted": False,
                    "first_seen": None,
                    "last_seen": None,
                    "ObjectReference": [],
                    "Attribute": [
                        {
                            "id": "17276",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "0f761150-c186-4bf6-8200-58d10c0a5fd1",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "comments",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "This is an example comment.",
                            "Galaxy": [],
                            "ShadowAttribute": [
                                {
                                    "id": "62",
                                    "type": "text",
                                    "category": "Other",
                                    "to_ids": False,
                                    "uuid": "0f761150-c186-4bf6-8200-58d10c0a5fd1",
                                    "event_uuid": "320d4589-cd71-4722-aa28-ea5530e99830",
                                    "event_id": "170",
                                    "old_id": "17276",
                                    "comment": "",
                                    "org_id": "8",
                                    "proposal_to_delete": False,
                                    "timestamp": "1762174322",
                                    "first_seen": None,
                                    "last_seen": None,
                                    "value": "Change comment",
                                    "Org": {"id": "8", "name": "org-10", "uuid": "e6e15f2d-45c7-4578-b824-9e4114ebd847", "local": True},
                                }
                            ],
                        },
                        {
                            "id": "17277",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "b0a402f8-8ff9-4377-a731-ea819f986282",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "description",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "<no_data>",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17278",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "cdcafe64-9640-4ed2-b101-c24a438af21e",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "id",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "320d4589-cd71-4722-aa28-ea5530e99830",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17279",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "c9f73424-d8a9-480e-b703-26a1e898a045",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "links",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "{'link': 'no_data', 'news_item_id': '<no_data>'}",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17280",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "8ddf62d3-e7e4-4c8d-bb45-2016b2353c90",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "summary",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "This is an example summary.",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17281",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "4323013f-e924-4e0b-bbe4-f400a26699e1",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Afghanistan", "tag_type": "Location"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17282",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "411c4efe-d8b7-4c18-8e17-b3db77791e60",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Alexander Dobrindt", "tag_type": "Person"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17283",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "e3fa2e97-4ad1-404f-84a9-e6b7f2153bc1",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Alexander Janda", "tag_type": "Person"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17284",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "a34cdd7c-69a0-440c-b2bb-69b5f755d305",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "BHAG", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17285",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "d3dff3b3-0fb3-444c-85b7-219f1f5a5750",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "BKA", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17286",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "8a36274b-7257-42c1-b019-40b29f461d23",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "BMI", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17287",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "a150602f-2229-4cba-887c-d94335321692",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "BMK\\u00d6S", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17288",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "a12f7e74-7271-4730-87f8-c82a94eecfc9",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Buchhaltungsagentur des Bundes", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17289",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "2a3fe920-8ba4-4c8c-8000-154a8527e38e",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Bundeskanzleramt", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17290",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "16b6c08e-1a55-45ba-9604-f41b566b1658",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Bundesministerium f\\u00fcr Inneres", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17291",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "0d41b3e0-6060-4a60-a5b5-873984447fe3",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Bundesministerium f\\u00fcr Kunst, Kultur, \\u00f6ffentlichen Dienst und Sport", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17292",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "c5d7638c-0a39-41f4-aead-07d307adc482",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Cloudflight", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17293",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "3aaf249f-d4f1-4b64-bb6b-e121e83714ba",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Europa", "tag_type": "Location"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17294",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "0199eaac-113b-4c4d-931a-81da3813b473",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Gerhard Karner", "tag_type": "Person"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17295",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "f222037e-8633-46f2-be97-bf4f744f77cb",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Innenministeriums", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17296",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "cdb2ab91-4b96-430b-a4b9-ab65660fde58",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "KS\\u00d6", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17297",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "d0d1981c-ccf9-449a-97d2-23a508ebd98c",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Karl Schl\\u00f6gl", "tag_type": "Person"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17298",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "fa9e0ddf-954a-46f2-9553-eccaa7402abb",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Kompetenzzentrum Sicheres \\u00d6sterreich", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17299",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "366efea7-eba3-4b98-87ad-e6b9242c1b06",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Luxemburg", "tag_type": "Location"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17300",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "e69243ec-e3e8-402f-b2f0-edd5de491945",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Marc Torben Hofmann", "tag_type": "Person"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17301",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "b9b3841b-88f4-423c-949c-794ed0e2bdef",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Michael H\\u00f6llerer", "tag_type": "Person"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17302",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "6ca27b96-050e-4226-b792-095330934ad4",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Raiffeisen Forum", "tag_type": "Location"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17303",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "295bbbbc-f835-4bfe-b23b-28e42a6dea46",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Raiffeisenlandesbank Nieder\\u00f6sterreich", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17304",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "0fa0a0ec-3524-46c3-9198-b7aabdf31eaf",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Smartphone", "tag_type": "Product"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17305",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "7efd499a-e22e-40dd-9762-0fb8ca71450b",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Sprengmitteln", "tag_type": "Product"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17306",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "77d9deef-b606-405b-9e80-eef72ce747c2",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Syrien", "tag_type": "Location"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17307",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "cf0da4ab-1558-48d3-a258-ce15a619a150",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Tageszeitungen", "tag_type": "Product"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17308",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "cdfe8fd6-f096-4ef0-a2da-9806f2f7e3da",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "Waffen", "tag_type": "Product"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17309",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "b3e42fbc-fe1a-47fd-ad81-e9ec3a7cbe23",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "\\u00d6IF", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17310",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "5b81c8e8-e92c-4207-92db-3f391a3ce94a",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "\\u00d6sterreich", "tag_type": "Location"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17311",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "079cb8ad-3e80-439e-8214-c6c74b017572",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "tags",
                            "first_seen": None,
                            "last_seen": None,
                            "value": '{"name": "\\u00d6sterreichischen Integrationsfonds", "tag_type": "Organization"}',
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17312",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "85ceea22-310a-4db9-9305-d3b678356241",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "title",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "Rat der Innenminister in Luxemburg: Karner fordert Abschiebungen nach Syrien aus ganz Europa",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17313",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "ffbb3272-346c-4b0c-af7c-ae9bfeba10aa",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "attributes",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "{'key': 'TLP', 'value': 'clear'}",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                        {
                            "id": "17314",
                            "type": "text",
                            "category": "Other",
                            "to_ids": False,
                            "uuid": "de89400e-03f0-4a31-bade-695be20400c5",
                            "event_id": "170",
                            "distribution": "5",
                            "timestamp": "1760568943",
                            "comment": "",
                            "sharing_group_id": "0",
                            "deleted": False,
                            "disable_correlation": False,
                            "object_id": "767",
                            "object_relation": "attributes",
                            "first_seen": None,
                            "last_seen": None,
                            "value": "{'key': 'misp_event_uuid', 'value': '320d4589-cd71-4722-aa28-ea5530e99830'}",
                            "Galaxy": [],
                            "ShadowAttribute": [],
                        },
                    ],
                },
            ],
            "EventReport": [
                {
                    "id": "154",
                    "uuid": "10d6640e-0d3d-4710-ad82-b69cd593c3ea",
                    "event_id": "170",
                    "name": "Rat der Innenminister in Luxemburg: Karner fordert Abschiebungen nach Syrien aus ganz Europa",
                    "content": "# Story description\n\n\n# Story comment",
                    "distribution": "5",
                    "sharing_group_id": "0",
                    "timestamp": "1760568797",
                    "deleted": False,
                }
            ],
            "CryptographicKey": [],
        }
    }
]
