upstream taranis_alpha {
  server 127.0.0.1:8081;
}

upstream taranis_bravo {
  server 127.0.0.1:8082;
}

upstream taranis_charlie {
  server 127.0.0.1:8083;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
    listen 80;
    server_name alpha.local.taranis.ai;

    client_max_body_size 50m;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    location /collaboration/ws {
        proxy_pass http://taranis_alpha;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 24h;
        proxy_send_timeout 24h;
        proxy_buffering off;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://taranis_alpha;
        proxy_redirect off;
    }
}

server {
    listen 80;
    server_name bravo.local.taranis.ai;

    client_max_body_size 50m;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    location /collaboration/ws {
        proxy_pass http://taranis_bravo;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 24h;
        proxy_send_timeout 24h;
        proxy_buffering off;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://taranis_bravo;
        proxy_redirect off;
    }
}

server {
    listen 80;
    server_name charlie.local.taranis.ai;

    client_max_body_size 50m;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    location /collaboration/ws {
        proxy_pass http://taranis_charlie;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 24h;
        proxy_send_timeout 24h;
        proxy_buffering off;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://taranis_charlie;
        proxy_redirect off;
    }
}
