from models.base import TaranisBaseModel

class Asset(TaranisBaseModel):
    _core_endpoint = ...
    _model_name = ...
    _search_fields = ...
    _pretty_name = ...
    id: str | None = ...
    name: str | None = ...
    description: str | None = ...
    serial: str | None = ...
    asset_group_id: str | None = ...
    asset_cpes: list[str] = ...
    vulnerabilities: list[str] = ...
    vulnerabilities_count: int | None = ...
