from datetime import datetime
from typing import Any, ClassVar, Final

from models.assess import Story
from models.base import TaranisBaseModel

class ReportItemCpe(TaranisBaseModel):
    id: str | None = ...
    value: str

class ReportItemAttribute(TaranisBaseModel):
    id: str | None = ...
    attribute: dict[str, str] | None = ...
    attribute_id: str | None = ...
    attribute_group_id: str | None = ...
    title: str | None = ...
    description: str | None = ...
    index: int | None = ...
    required: bool | None = ...
    value: str | None = ...
    type: str | None = ...
    render_data: dict[str, Any] = ...

class ReportItemAttributeGroup(TaranisBaseModel):
    title: str
    attributes: list[ReportItemAttribute] = ...

class ReportItem(TaranisBaseModel):
    _core_endpoint: ClassVar[str] = ...
    _model_name: ClassVar[str] = ...
    _search_fields: Final[list[str]] = ...
    _pretty_name: ClassVar[str] = ...
    id: str | None = ...
    title: str | None = ...
    created: datetime | None = ...
    last_updated: datetime | None = ...
    completed: bool | None = ...
    user_id: str | None = ...
    report_item_type_id: str | None = ...
    report_item_type: str | None = ...
    stories: list[Story | str] | None = ...
    used_story_ids: list[str] = ...
    grouped_attributes: list[ReportItemAttributeGroup] | None = ...
    attributes: list[ReportItemAttribute] | dict[str, str] = ...
    report_item_cpes: list[ReportItemCpe] | None = ...
