FROM nginxinc/nginx-unprivileged:1.29.2

ENV TARANIS_CORE_UPSTREAM=core:8080
ENV TARANIS_FRONTEND_UPSTREAM=frontend:8080
ENV TARANIS_REALTIME_UPSTREAM=centrifugo:8000
ENV TARANIS_BASE_PATH=/

COPY ./src/ingress/extras/default.conf.template /etc/nginx/default.conf.template
COPY ./src/ingress/extras/10-base_uri_envsubst_entrypoint.sh /docker-entrypoint.d/
COPY ./src/ingress/extras/upstream.html /usr/share/nginx/html/taranis/upstream.html
