"""empty message

Revision ID: 094b85ef4dcf
Revises: 7607d7d98f71
Create Date: 2021-11-22 11:14:22.259612

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "094b85ef4dcf"
down_revision = "7607d7d98f71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = inspect(bind)
    columns = insp.get_columns("osint_source_group")
    column_names = [c["name"] for c in columns]
    if "default" not in column_names:
        op.add_column(
            "osint_source_group",
            sa.Column("default", sa.Boolean(), nullable=True, default=False),
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("osint_source_group", "default")
    # ### end Alembic commands ###
