apiVersion: v1
kind: Secret
metadata:
  name: taranis-secrets
type: Opaque
stringData:
  JWT_SECRET_KEY: CHANGE_ME_LONG_RANDOM_JWT_SECRET
  API_KEY: CHANGE_ME_CORE_API_KEY
  BOT_API_KEY: CHANGE_ME_BOT_API_KEY
  LLM_API_KEY: CHANGE_ME_LLM_API_KEY
  PRE_SEED_PASSWORD_ADMIN: CHANGE_ME_ADMIN_PASSWORD
  PRE_SEED_PASSWORD_USER: CHANGE_ME_DEFAULT_USER_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_URL: CHANGE_ME_DATABASE_HOSTNAME
  DB_DATABASE: CHANGE_ME_DATABASE_NAME
  DB_USER: CHANGE_ME_DATABASE_USER
  DB_PASSWORD: CHANGE_ME_DATABASE_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: taranis-rabbitmq-credentials
type: Opaque
stringData:
  QUEUE_BROKER_HOST: CHANGE_ME_RABBITMQ_HOSTNAME
  QUEUE_BROKER_USER: CHANGE_ME_RABBITMQ_USER
  QUEUE_BROKER_PASSWORD: CHANGE_ME_RABBITMQ_PASSWORD
