apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-config.yaml
  - 01-secrets.yaml
  - 05-network-policies.yaml
  - 10-storage.yaml
  - 20-services.yaml
  - 30-deployments.yaml
  - 40-ingress.yaml
