workers = [
    {
        "name": "RSS Collector",
        "description": "Collector for gathering data from RSS feeds",
        "parameters": [
            {"parameter": "FEED_URL", "rules": "required"},
            {"parameter": "USER_AGENT"},
            {"parameter": "CONTENT_LOCATION"},
            {"parameter": "XPATH"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
            {"parameter": "DIGEST_SPLITTING", "type": "switch"},
        ],
        "type": "RSS_COLLECTOR",
    },
    {
        "name": "EMAIL Collector",
        "description": "Collector for gathering data from emails",
        "parameters": [
            {"parameter": "EMAIL_SERVER_TYPE"},
            {"parameter": "EMAIL_SERVER_HOSTNAME"},
            {"parameter": "EMAIL_SERVER_PORT", "type": "number"},
            {"parameter": "EMAIL_USERNAME"},
            {"parameter": "EMAIL_PASSWORD"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "type": "EMAIL_COLLECTOR",
    },
    {
        "name": "Simple Web Collector",
        "description": "Collector for gathering data from a web site via python requests",
        "parameters": [
            {"parameter": "WEB_URL", "rules": "required"},
            {"parameter": "USER_AGENT"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "XPATH"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
        ],
        "type": "SIMPLE_WEB_COLLECTOR",
    },
    {
        "name": "Manual",
        "description": "Manual source for creating news items via UI",
        "parameters": [
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
        ],
        "type": "MANUAL_COLLECTOR",
    },
    {
        "description": "Collector for gathering data from web page",
        "name": "Selenium Web Collector",
        "parameters": [
            "WEB_URL",
            "WEBDRIVER",
            "TOR",
            "USER_AGENT",
            "PROXY_SERVER",
            "REFRESH_INTERVAL",
            "AUTH_USERNAME",
            "AUTH_PASSWORD",
            "CLIENT_CERT_DIR",
            "POPUP_CLOSE_SELECTOR",
            "TITLE_SELECTOR",
            "NEXT_BUTTON_SELECTOR",
            "LOAD_MORE_BUTTON_SELECTOR",
            "PAGINATION_LIMIT",
            "ARTICLE_DESCRIPTION_SELECTOR",
            "ARTICLE_FULL_TEXT_SELECTOR",
            "SINGLE_ARTICLE_LINK_SELECTOR",
            "AUTHOR_SELECTOR",
            "PUBLISHED_SELECTOR",
            "ATTACHMENT_SELECTOR",
            "WORD_LIMIT",
            "ADDITIONAL_ID_SELECTOR",
        ],
        "type": "SELENIUM_WEB_COLLECTOR",
    },
    {
        "description": "Collector for gathering data from Request Tracker",
        "name": "RT Collector",
        "parameters": [
            {"parameter": "BASE_URL", "rules": "required"},
            {"parameter": "RT_TOKEN", "rules": "required"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
        ],
        "type": "RT_COLLECTOR",
    },
    {
        "type": "ANALYST_BOT",
        "name": "Analyst Bot",
        "parameters": [
            {"parameter": "REGULAR_EXPRESSION"},
            {"parameter": "ATTRIBUTE_NAME"},
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for news items analysis",
    },
    {
        "type": "GROUPING_BOT",
        "name": "Grouping Bot",
        "parameters": [
            {"parameter": "REGULAR_EXPRESSION"},
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for grouping news items into aggregates",
    },
    {
        "type": "NLP_BOT",
        "name": "NLP Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for naturale language processing of news items",
    },
    {
        "type": "IOC_BOT",
        "name": "IOC Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for extracting indicators of compromise from news items",
    },
    {
        "type": "TAGGING_BOT",
        "name": "Tagging Bot",
        "parameters": [
            {"parameter": "KEYWORDS"},
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for tagging news items",
    },
    {
        "type": "STORY_BOT",
        "name": "Story Clustering Bot",
        "parameters": [
            {
                "parameter": "ITEM_FILTER",
            },
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for Story Clustering",
    },
    {
        "type": "SUMMARY_BOT",
        "name": "Summary generation Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for summarizing news items aggregates",
    },
    {
        "type": "WORDLIST_BOT",
        "name": "Wordlist Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "TAGGING_WORDLISTS", "type": "table"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
        "description": "Bot for tagging news items by wordlist",
    },
    {
        "type": "PDF_PRESENTER",
        "description": "Presenter for generating PDF documents",
        "parameters": ["TEMPLATE_PATH"],
        "name": "PDF Presenter",
    },
    {
        "type": "HTML_PRESENTER",
        "name": "HTML Presenter",
        "description": "Presenter for generating html documents",
        "parameters": ["TEMPLATE_PATH"],
    },
    {
        "type": "TEXT_PRESENTER",
        "name": "TEXT Presenter",
        "description": "Presenter for generating text documents",
        "parameters": ["TEMPLATE_PATH"],
    },
    {
        "type": "JSON_PRESENTER",
        "name": "JSON Presenter",
        "description": "Presenter for generating json documents",
        "parameters": ["TEMPLATE_PATH"],
    },
    {
        "type": "FTP_PUBLISHER",
        "name": "FTP Publisher",
        "description": "Publisher for publishing to FTP server",
        "parameters": ["FTP_URL"],
    },
    {
        "type": "EMAIL_PUBLISHER",
        "name": "EMAIL Publisher",
        "description": "Publisher for publishing by email",
        "parameters": [
            {"parameter": "SMTP_SERVER_ADDRESS", "rules": "required"},
            {"parameter": "SMTP_SERVER_PORT", "type": "number"},
            {"parameter": "SERVER_TLS", "type": "switch"},
            {"parameter": "EMAIL_USERNAME"},
            {"parameter": "EMAIL_PASSWORD"},
            {"parameter": "EMAIL_SENDER", "rules": "required,email"},
            {"parameter": "EMAIL_RECIPIENT", "rules": "required,email"},
            {"parameter": "EMAIL_SUBJECT"},
        ],
    },
    {
        "type": "TWITTER_PUBLISHER",
        "name": "Twitter Publisher",
        "description": "Publisher for publishing to Twitter account",
        "parameters": ["TWITTER_API_KEY", "TWITTER_API_KEY_SECRET", "TWITTER_ACCESS_TOKEN", "TWITTER_ACCESS_TOKEN_SECRET"],
    },
    {
        "type": "WORDPRESS_PUBLISHER",
        "name": "Wordpress Publisher",
        "description": "Publisher for publishing on Wordpress webpage",
        "parameters": ["WP_URL", "WP_USER", "WP_PYTHON_APP_SECRET"],
    },
    {
        "type": "MISP_PUBLISHER",
        "name": "MISP Publisher",
        "description": "Publisher for publishing in MISP",
        "parameters": ["MISP_URL", "MISP_API_KEY"],
    },
]


bots = [
    {
        "name": "Wordlist Bot",
        "description": "Bot for tagging news items by wordlist",
        "type": "WORDLIST_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
    },
    {
        "name": "IOC BOT",
        "description": "Bot for Tagging news items",
        "type": "IOC_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
    },
    {
        "name": "NLP Tagging BOT",
        "description": "Bot for Tagging Items via NLP",
        "type": "NLP_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "number"},
        ],
    },
    {
        "name": "Story BOT",
        "description": "Bot for story clustering",
        "type": "STORY_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER", "value": "limit=666"},
        ],
    },
    {
        "name": "Summary BOT",
        "description": "Bot for summarizing stories",
        "type": "SUMMARY_BOT",
    },
]

report_types = [
    {
        "id": 1,
        "title": "OSINT Report",
        "description": "Example OSINT Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Summary",
                "description": "Summary",
                "index": 0,
                "attribute_group_items": [
                    {"title": "Summary", "description": "Summary", "index": 0, "attribute": "Text Area"},
                    {"title": "Sector trends", "description": "Sector trends", "index": 1, "attribute": "Text Area"},
                    {"title": "Vulnerabilities trends", "description": "Vulnerabilities trends", "index": 2, "attribute": "Text Area"},
                    {"title": "Ransomware trends", "description": "Ransomware trends", "index": 3, "attribute": "Text Area"},
                    {"title": "Date published", "description": "Date published", "index": 4, "attribute": "Date"},
                    {"title": "Threat level", "description": "Threat level", "index": 5, "attribute": "MISP Event Threat Level"},
                    {"title": "TLP", "description": "Traffic Light Protocol", "index": 6, "attribute": "TLP"},
                ],
            },
            {
                "title": "Ransomware",
                "description": "Ransomware",
                "index": 1,
                "attribute_group_items": [
                    {"title": "Ransomware", "description": "Ransomware", "index": 0, "attribute": "Text"},
                    {"title": "Actor", "description": "Actor", "index": 1, "attribute": "Text"},
                    {"title": "Sector", "description": "Sector", "index": 2, "attribute": "NIS Sectors"},
                    {"title": "Comment", "description": "Comment", "index": 3, "attribute": "Text Area"},
                ],
            },
        ],
    },
    {
        "id": 2,
        "title": "Disinformation",
        "description": "Example Disinformation Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Summary",
                "description": "Summary",
                "index": 0,
                "attribute_group_items": [
                    {"title": "Title", "description": "Disinformation campaign", "index": 0, "attribute": "Text"},
                    {"title": "Quote", "description": "Quote", "index": 1, "attribute": "Text Area"},
                    {"title": "Reach", "description": "Exposed people", "index": 2, "attribute": "Number"},
                    {"title": "Date started", "description": "Campaign started", "index": 3, "attribute": "Date"},
                    {"title": "Proof", "description": "Screenshots, ...", "index": 4, "attribute": "Attachment"},
                ],
            },
            {
                "title": "Ransomware",
                "description": "Ransomware",
                "index": 1,
                "attribute_group_items": [
                    {"title": "Ransomware", "description": "Ransomware", "index": 0, "attribute": "Text"},
                    {"title": "Actor", "description": "Actor", "index": 1, "attribute": "Text"},
                    {"title": "Sector", "description": "Sector", "index": 2, "attribute": "NIS Sectors"},
                    {"title": "Comment", "description": "Comment", "index": 3, "attribute": "Text Area"},
                ],
            },
        ],
    },
    {
        "id": 3,
        "title": "Vulnerability Report",
        "description": "Example Vulnerability Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Vulnerability",
                "description": "Vulnerability",
                "index": 0,
                "attribute_group_items": [
                    {
                        "title": "CVSS",
                        "description": "Common Vulnerability Scoring System",
                        "index": 0,
                        "attribute": "CVSS",
                    },
                    {
                        "title": "TLP",
                        "description": "Traffic Light Protocol",
                        "index": 1,
                        "attribute": "TLP",
                    },
                    {
                        "title": "Confidentiality",
                        "description": "Confidentiality",
                        "index": 2,
                        "attribute": "Confidentiality",
                    },
                    {
                        "title": "Description",
                        "description": "Description",
                        "index": 3,
                        "attribute": "Text Area",
                    },
                    {
                        "title": "Exposure Date",
                        "description": "Exposure Date",
                        "index": 4,
                        "attribute": "Date",
                    },
                    {
                        "title": "Update Date",
                        "description": "Update Date",
                        "index": 5,
                        "attribute": "Date",
                    },
                    {
                        "title": "CVE",
                        "description": "CVE",
                        "index": 6,
                        "attribute": "CVE",
                    },
                    {
                        "title": "Impact",
                        "description": "Impact",
                        "index": 7,
                        "attribute": "Impact",
                    },
                    {
                        "title": "Links",
                        "description": "Links",
                        "index": 8,
                        "multiple": True,
                        "attribute": "Text",
                    },
                ],
            },
            {
                "title": "Identify and Act",
                "description": "Identify and Act",
                "index": 1,
                "attribute_group_items": [
                    {
                        "title": "Affected Systems",
                        "description": "Affected Systems",
                        "index": 0,
                        "multiple": True,
                        "attribute": "CPE",
                    },
                    {
                        "title": "IOC",
                        "description": "IOC",
                        "index": 1,
                        "multiple": True,
                        "attribute": "Text",
                    },
                    {
                        "title": "Recommendations",
                        "description": "Recommendations",
                        "index": 2,
                        "attribute": "Text Area",
                    },
                ],
            },
        ],
    },
    {
        "id": 4,
        "title": "CERT Report",
        "description": "Example CERT Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Data",
                "description": "Data",
                "index": 0,
                "attribute_group_items": [
                    {"title": "date", "description": "Date", "index": 0, "attribute": "Text"},
                    {"title": "timeframe", "description": "Timeframe", "index": 1, "attribute": "Text"},
                    {"title": "handler", "description": "Handler", "index": 2, "attribute": "Text"},
                    {"title": "co_handler", "description": "CO-Handler", "index": 3, "attribute": "Text"},
                    {"title": "news", "description": "News", "index": 4, "attribute": "Story", "multiple": True},
                    {"title": "vulnerabilities", "description": "Vulnerabilities", "index": 5, "attribute": "Story", "multiple": True},
                ],
            }
        ],
    },
]


product_types = [
    {
        "title": "Default PDF Presenter",
        "description": "Default PDF Presenter",
        "type": "PDF_PRESENTER",
        "parameters": [
            {"parameter": "TEMPLATE_PATH", "value": "pdf_template.html"},
        ],
        "report_types": [1, 2, 3, 4],
    },
    {
        "title": "Default TEXT Presenter",
        "description": "Default TEXT Presenter",
        "type": "TEXT_PRESENTER",
        "parameters": [
            {"parameter": "TEMPLATE_PATH", "value": "text_template.txt"},
        ],
        "report_types": [1, 2, 3, 4],
    },
    {
        "title": "CERT Daily Report",
        "description": "cert.at Daily Report HTML",
        "type": "HTML_PRESENTER",
        "parameters": [
            {"parameter": "TEMPLATE_PATH", "value": "cert_at_daily_report.html"},
        ],
        "report_types": [4],
    },
]

word_lists = [
    {
        "name": "CVE Vendors",
        "description": "List of vendors that are known to be affected by a CVE.",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/vendors.json",
        "usage": 4,
    },
    {
        "name": "CVE Products",
        "description": "List of products that are known to be affected by a CVE.",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/products.json",
        "usage": 4,
    },
    {
        "name": "Countries",
        "description": "List of Countries",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/countries.json",
        "usage": 4,
    },
    {
        "name": "Austrian Municipalities",
        "description": "List of Austrian Municipalities",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/austrian_municipalities.json",
    },
    {
        "name": "Common Cyber Security Terms",
        "description": "List of common cyber security terms",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/common.json",
        "usage": 4,
    },
    {
        "name": "APT Groups",
        "description": "List of Advanced Persistent Threat Groups",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/apt.json",
        "usage": 4,
    },
    {
        "name": "Länder",
        "description": "Liste aller Länder",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/countries_german.json",
        "usage": 4,
    },
    {
        "name": "Internationale Organisationen",
        "description": "Wichtigsten internationalen Organisationen",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/ngos_german.json",
        "usage": 4,
    },
    {
        "name": "Unternehmen Österreich",
        "description": "Größten Unternehmen in Österreich",
        "link": "https://raw.githubusercontent.com/taranis-ai/wordlists/master/output/companies_austria.json",
        "usage": 4,
    },
]


permissions = [
    ("ADMIN_OPERATIONS", "Admin operations", "Admin operations"),
    ("ASSESS_ACCESS", "Assess access", "Access to Assess module"),
    ("ASSESS_CREATE", "Assess create", "Create news item"),
    ("ASSESS_UPDATE", "Assess update", "Update news item"),
    ("ASSESS_DELETE", "Assess delete", "Delete news item"),
    ("ANALYZE_ACCESS", "Analyze access", "Access to Analyze module"),
    ("ANALYZE_CREATE", "Analyze create", "Create report item"),
    ("ANALYZE_UPDATE", "Analyze update", "Update report item"),
    ("ANALYZE_DELETE", "Analyze delete", "Delete report item"),
    ("PUBLISH_ACCESS", "Publish access", "Access to publish module"),
    ("PUBLISH_CREATE", "Publish create", "Create product"),
    ("PUBLISH_UPDATE", "Publish update", "Update product"),
    ("PUBLISH_DELETE", "Publish delete", "Delete product"),
    ("PUBLISH_PRODUCT", "Publish product", "Publish product"),
    ("CONFIG_ACCESS", "Configuration access", "Access to Configuration module"),
    (
        "CONFIG_ORGANIZATION_ACCESS",
        "Config organizations access",
        "Access to attributes configuration",
    ),
    (
        "CONFIG_ORGANIZATION_CREATE",
        "Config organization create",
        "Create organization configuration",
    ),
    (
        "CONFIG_ORGANIZATION_UPDATE",
        "Config organization update",
        "Update organization configuration",
    ),
    (
        "CONFIG_ORGANIZATION_DELETE",
        "Config organization delete",
        "Delete organization configuration",
    ),
    ("CONFIG_USER_ACCESS", "Config users access", "Access to users configuration"),
    ("CONFIG_USER_CREATE", "Config user create", "Create user configuration"),
    ("CONFIG_USER_UPDATE", "Config user update", "Update user configuration"),
    ("CONFIG_USER_DELETE", "Config user delete", "Delete user configuration"),
    ("CONFIG_ROLE_ACCESS", "Config roles access", "Access to roles configuration"),
    ("CONFIG_ROLE_CREATE", "Config role create", "Create role configuration"),
    ("CONFIG_ROLE_UPDATE", "Config role update", "Update role configuration"),
    ("CONFIG_ROLE_DELETE", "Config role delete", "Delete role configuration"),
    ("CONFIG_ACL_ACCESS", "Config acls access", "Access to acls configuration"),
    ("CONFIG_ACL_CREATE", "Config acl create", "Create acl configuration"),
    ("CONFIG_ACL_UPDATE", "Config acl update", "Update acl configuration"),
    ("CONFIG_ACL_DELETE", "Config acl delete", "Delete acl configuration"),
    (
        "CONFIG_PRODUCT_TYPE_ACCESS",
        "Config product types access",
        "Access to product types configuration",
    ),
    (
        "CONFIG_PRODUCT_TYPE_CREATE",
        "Config product type create",
        "Create product type configuration",
    ),
    (
        "CONFIG_PRODUCT_TYPE_UPDATE",
        "Config product type update",
        "Update product type configuration",
    ),
    (
        "CONFIG_PRODUCT_TYPE_DELETE",
        "Config product type delete",
        "Delete product type configuration",
    ),
    (
        "CONFIG_ATTRIBUTE_ACCESS",
        "Config attributes access",
        "Access to attributes configuration",
    ),
    (
        "CONFIG_ATTRIBUTE_CREATE",
        "Config attribute create",
        "Create attribute configuration",
    ),
    (
        "CONFIG_ATTRIBUTE_UPDATE",
        "Config attribute update",
        "Update attribute configuration",
    ),
    (
        "CONFIG_ATTRIBUTE_DELETE",
        "Config attribute delete",
        "Delete attribute configuration",
    ),
    (
        "CONFIG_REPORT_TYPE_ACCESS",
        "Config report item types access",
        "Access to report item types configuration",
    ),
    (
        "CONFIG_REPORT_TYPE_CREATE",
        "Config report item type create",
        "Create report item type configuration",
    ),
    (
        "CONFIG_REPORT_TYPE_UPDATE",
        "Config report item type update",
        "Update report item type configuration",
    ),
    (
        "CONFIG_REPORT_TYPE_DELETE",
        "Config report item type delete",
        "Delete report item type configuration",
    ),
    (
        "CONFIG_WORD_LIST_ACCESS",
        "Config word lists access",
        "Access to word lists configuration",
    ),
    (
        "CONFIG_WORD_LIST_CREATE",
        "Config word list create",
        "Create word list configuration",
    ),
    (
        "CONFIG_WORD_LIST_UPDATE",
        "Config word list update",
        "Update word list configuration",
    ),
    (
        "CONFIG_WORD_LIST_DELETE",
        "Config word list delete",
        "Delete word list configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_ACCESS",
        "Config OSINT source access",
        "Access to OSINT sources configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_CREATE",
        "Config OSINT source create",
        "Create OSINT source configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_UPDATE",
        "Config OSINT source update",
        "Update OSINT source configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_DELETE",
        "Config OSINT source delete",
        "Delete OSINT source configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_GROUP_ACCESS",
        "Config OSINT source group access",
        "Access to OSINT sources groups configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_GROUP_CREATE",
        "Config OSINT source group create",
        "Create OSINT source group configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_GROUP_UPDATE",
        "Config OSINT source group update",
        "Update OSINT source group configuration",
    ),
    (
        "CONFIG_OSINT_SOURCE_GROUP_DELETE",
        "Config OSINT source group delete",
        "Delete OSINT source group configuration",
    ),
    (
        "CONFIG_PUBLISHER_ACCESS",
        "Config publisher presets access",
        "Access to publisher presets configuration",
    ),
    (
        "CONFIG_PUBLISHER_CREATE",
        "Config publisher preset create",
        "Create publisher preset configuration",
    ),
    (
        "CONFIG_PUBLISHER_UPDATE",
        "Config publisher preset update",
        "Update publisher preset configuration",
    ),
    (
        "CONFIG_PUBLISHER_DELETE",
        "Config publisher preset delete",
        "Delete publisher preset configuration",
    ),
    (
        "CONFIG_BOT_ACCESS",
        "Config bots access",
        "Access to bots configuration",
    ),
    (
        "CONFIG_BOT_CREATE",
        "Config bot create",
        "Create bot configuration",
    ),
    (
        "CONFIG_BOT_UPDATE",
        "Config bot update",
        "Update bot configuration",
    ),
    (
        "CONFIG_BOT_DELETE",
        "Config bot delete",
        "Delete bot configuration",
    ),
    (
        "CONFIG_PUBLISHER_ACCESS",
        "Config publisher presets access",
        "Access to publisher presets configuration",
    ),
    (
        "CONFIG_PUBLISHER_CREATE",
        "Config publisher preset create",
        "Create publisher preset configuration",
    ),
    (
        "CONFIG_PUBLISHER_UPDATE",
        "Config publisher preset update",
        "Update publisher preset configuration",
    ),
    (
        "CONFIG_PUBLISHER_DELETE",
        "Config publisher preset delete",
        "Delete publisher preset configuration",
    ),
    ("ASSETS_ACCESS", "Assets access", "Access to Assets"),
    (
        "ASSETS_CREATE",
        "My Assets create",
        "Creation of new Assets",
    ),
    (
        "ASSETS_CONFIG",
        "My Assets config",
        "Configuration of access and groups",
    ),
    (
        "CONFIG_WORKER_ACCESS",
        "Access to workers",
        "Access to workers configuration",
    ),
    (
        "CONFIG_API_ACCESS",
        "Config API access",
        "Access to API configuration",
    ),
]

attrs_with_enum = [
    {
        "name": "Confidentiality",
        "description": "Radio box for confidentiality level",
        "type": "RADIO",
        "attribute_enums": [
            {"index": 0, "value": "UNRESTRICTED", "description": ""},
            {"index": 1, "value": "CLASSIFIED", "description": ""},
            {"index": 2, "value": "CONFIDENTIAL", "description": ""},
            {"index": 3, "value": "SECRET", "description": ""},
            {"index": 4, "value": "TOP SECRET", "description": ""},
        ],
    },
    {
        "name": "Impact",
        "description": "Combo box for impact level",
        "type": "ENUM",
        "attribute_enums": [
            {
                "index": 0,
                "value": "Malicious code execution affecting CIA of the system",
                "description": "",
            },
            {"index": 1, "value": "Malicious code execution", "description": ""},
            {"index": 2, "value": "Denial of service", "description": ""},
            {"index": 3, "value": "Privilege escalation", "description": ""},
            {"index": 4, "value": "Information exposure", "description": ""},
            {
                "index": 5,
                "value": "Unauthorized access to the system",
                "description": "",
            },
            {"index": 6, "value": "Unauthorized change in system", "description": ""},
        ],
    },
    {
        "name": "MISP Event Distribution",
        "description": "Combo box for MISP event distribution",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Your organisation only", "description": ""},
            {"index": 1, "value": "This community only", "description": ""},
            {"index": 2, "value": "Connected communities", "description": ""},
            {"index": 3, "value": "All communities", "description": ""},
        ],
    },
    {
        "name": "MISP Event Threat Level",
        "description": "Combo box for MISP event threat level",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "High", "description": ""},
            {"index": 1, "value": "Medium", "description": ""},
            {"index": 2, "value": "Low", "description": ""},
            {"index": 3, "value": "Undefined", "description": ""},
        ],
    },
    {
        "name": "MISP Event Analysis",
        "description": "Combo box for MISP event analysis",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Initial", "description": ""},
            {"index": 1, "value": "Ongoing", "description": ""},
            {"index": 2, "value": "Completed", "description": ""},
        ],
    },
    {
        "name": "MISP Attribute Category",
        "description": "Combo box for MISP attribute category",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Internal reference", "description": ""},
            {"index": 1, "value": "Targeting data", "description": ""},
            {"index": 2, "value": "Antivirus detection", "description": ""},
            {"index": 3, "value": "Payload delivery", "description": ""},
            {"index": 4, "value": "Artifacts dropped", "description": ""},
            {"index": 5, "value": "Payload installation", "description": ""},
            {"index": 6, "value": "Persistence mechanism", "description": ""},
            {"index": 7, "value": "Network activity", "description": ""},
            {"index": 8, "value": "Payload type", "description": ""},
            {"index": 9, "value": "Attribution", "description": ""},
            {"index": 10, "value": "External analysis", "description": ""},
            {"index": 11, "value": "Financial fraud", "description": ""},
            {"index": 12, "value": "Support Tool", "description": ""},
            {"index": 13, "value": "Social network", "description": ""},
            {"index": 14, "value": "Person", "description": ""},
            {"index": 15, "value": "Other", "description": ""},
        ],
    },
    {
        "name": "MISP Attribute Type",
        "description": "Combo box for MISP attribute type",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "md5", "description": ""},
            {"index": 1, "value": "sha1", "description": ""},
            {"index": 2, "value": "sha256", "description": ""},
            {"index": 3, "value": "filename", "description": ""},
            {"index": 4, "value": "pbd", "description": ""},
            {"index": 5, "value": "filename|md5", "description": ""},
            {"index": 6, "value": "filename|sha1", "description": ""},
            {"index": 7, "value": "filename|sha256", "description": ""},
            {"index": 8, "value": "ip-src", "description": ""},
            {"index": 9, "value": "ip-dst", "description": ""},
            {"index": 10, "value": "hostname", "description": ""},
            {"index": 11, "value": "domain", "description": ""},
            {"index": 12, "value": "domain|ip", "description": ""},
            {"index": 13, "value": "email-src", "description": ""},
            {"index": 14, "value": "eppn", "description": ""},
            {"index": 15, "value": "email-dst", "description": ""},
            {"index": 16, "value": "email-subject", "description": ""},
            {"index": 17, "value": "email-attachment", "description": ""},
            {"index": 18, "value": "email-body", "description": ""},
            {"index": 19, "value": "float", "description": ""},
            {"index": 20, "value": "url", "description": ""},
            {"index": 21, "value": "http-method", "description": ""},
            {"index": 22, "value": "user-agent", "description": ""},
            {"index": 23, "value": "ja3-fingerprint-md5", "description": ""},
            {"index": 24, "value": "hassh-md5", "description": ""},
            {"index": 25, "value": "hasshserver-md5", "description": ""},
            {"index": 26, "value": "reg-key", "description": ""},
            {"index": 27, "value": "regkey|value", "description": ""},
            {"index": 28, "value": "AS", "description": ""},
            {"index": 29, "value": "snort", "description": ""},
            {"index": 30, "value": "bro", "description": ""},
            {"index": 31, "value": "zeek", "description": ""},
            {"index": 32, "value": "community-id", "description": ""},
            {"index": 33, "value": "pattern-in-traffic", "description": ""},
            {"index": 34, "value": "pattern-in-memory", "description": ""},
            {"index": 35, "value": "yara", "description": ""},
            {"index": 36, "value": "stix2-pattern", "description": ""},
            {"index": 37, "value": "sigma", "description": ""},
            {"index": 38, "value": "gene", "description": ""},
            {"index": 39, "value": "kusto-query", "description": ""},
            {"index": 40, "value": "mime-type", "description": ""},
            {"index": 41, "value": "identity-card-number", "description": ""},
            {"index": 42, "value": "cookie", "description": ""},
            {"index": 43, "value": "vulnerability", "description": ""},
            {"index": 44, "value": "weakness", "description": ""},
            {"index": 45, "value": "link", "description": ""},
            {"index": 46, "value": "comment", "description": ""},
            {"index": 47, "value": "text", "description": ""},
            {"index": 48, "value": "hex", "description": ""},
            {"index": 49, "value": "other", "description": ""},
            {"index": 50, "value": "named pipe", "description": ""},
            {"index": 51, "value": "mutex", "description": ""},
            {"index": 52, "value": "target-user", "description": ""},
            {"index": 53, "value": "target-email", "description": ""},
            {"index": 54, "value": "target-machine", "description": ""},
            {"index": 55, "value": "target-org", "description": ""},
            {"index": 56, "value": "target-location", "description": ""},
            {"index": 57, "value": "target-external", "description": ""},
            {"index": 58, "value": "btc", "description": ""},
            {"index": 59, "value": "dash", "description": ""},
            {"index": 60, "value": "xmr", "description": ""},
            {"index": 61, "value": "iban", "description": ""},
            {"index": 62, "value": "bic", "description": ""},
            {"index": 63, "value": "bank-account-nr", "description": ""},
            {"index": 64, "value": "aba-rtn", "description": ""},
            {"index": 65, "value": "bin", "description": ""},
            {"index": 66, "value": "cc-number", "description": ""},
            {"index": 67, "value": "prtn", "description": ""},
            {"index": 68, "value": "phone-number", "description": ""},
            {"index": 69, "value": "threat-actor", "description": ""},
            {"index": 70, "value": "campaign-name", "description": ""},
            {"index": 71, "value": "campaign-id", "description": ""},
            {"index": 72, "value": "malware-type", "description": ""},
            {"index": 73, "value": "uri", "description": ""},
            {"index": 74, "value": "authentihash", "description": ""},
            {"index": 75, "value": "ssdeep", "description": ""},
            {"index": 76, "value": "implash", "description": ""},
            {"index": 77, "value": "pahash", "description": ""},
            {"index": 78, "value": "impfuzzy", "description": ""},
            {"index": 79, "value": "sha224", "description": ""},
            {"index": 80, "value": "sha384", "description": ""},
            {"index": 81, "value": "sha512", "description": ""},
            {"index": 82, "value": "sha512/224", "description": ""},
            {"index": 83, "value": "sha512/256", "description": ""},
            {"index": 84, "value": "tlsh", "description": ""},
            {"index": 85, "value": "cdhash", "description": ""},
            {"index": 86, "value": "filename|authentihash", "description": ""},
            {"index": 87, "value": "filename|ssdeep", "description": ""},
            {"index": 88, "value": "filename|implash", "description": ""},
            {"index": 89, "value": "filename|impfuzzy", "description": ""},
            {"index": 90, "value": "filename|pehash", "description": ""},
            {"index": 91, "value": "filename|sha224", "description": ""},
            {"index": 92, "value": "filename|sha384", "description": ""},
            {"index": 93, "value": "filename|sha512", "description": ""},
            {"index": 94, "value": "filename|sha512/224", "description": ""},
            {"index": 95, "value": "filename|sha512/256", "description": ""},
            {"index": 96, "value": "filename|tlsh", "description": ""},
            {"index": 97, "value": "windows-scheduled-task", "description": ""},
            {"index": 98, "value": "windows-service-name", "description": ""},
            {"index": 99, "value": "windows-service-displayname", "description": ""},
            {"index": 100, "value": "whois-registrant-email", "description": ""},
            {"index": 101, "value": "whois-registrant-phone", "description": ""},
            {"index": 102, "value": "whois-registrant-name", "description": ""},
            {"index": 103, "value": "whois-registrant-org", "description": ""},
            {"index": 104, "value": "whois-registrar", "description": ""},
            {"index": 105, "value": "whois-creation-date", "description": ""},
            {"index": 106, "value": "x509-fingerprint-sha1", "description": ""},
            {"index": 107, "value": "x509-fingerprint-md5", "description": ""},
            {"index": 108, "value": "x509-fingerprint-sha256", "description": ""},
            {"index": 109, "value": "dns-soa-email", "description": ""},
            {"index": 110, "value": "size-in-bytes", "description": ""},
            {"index": 111, "value": "counter", "description": ""},
            {"index": 112, "value": "datetime", "description": ""},
            {"index": 113, "value": "cpe", "description": ""},
            {"index": 114, "value": "port", "description": ""},
            {"index": 115, "value": "ip-dist|port", "description": ""},
            {"index": 116, "value": "ip-src|port", "description": ""},
            {"index": 117, "value": "hostname|port", "description": ""},
            {"index": 118, "value": "mac-address", "description": ""},
            {"index": 119, "value": "mac-eui-64", "description": ""},
            {"index": 120, "value": "email-dst-display-name", "description": ""},
            {"index": 121, "value": "email-src-display-name", "description": ""},
            {"index": 122, "value": "email-header", "description": ""},
            {"index": 123, "value": "email-reply-to", "description": ""},
            {"index": 124, "value": "email-x-mailer", "description": ""},
            {"index": 125, "value": "email-mime-boundary", "description": ""},
            {"index": 126, "value": "email-thread-index", "description": ""},
            {"index": 127, "value": "email-message-id", "description": ""},
            {"index": 128, "value": "github-username", "description": ""},
            {"index": 129, "value": "github-repository", "description": ""},
            {"index": 130, "value": "githzb-organisation", "description": ""},
            {"index": 131, "value": "jabber-id", "description": ""},
            {"index": 132, "value": "twitter-id", "description": ""},
            {"index": 133, "value": "first-name", "description": ""},
            {"index": 134, "value": "middle-name", "description": ""},
            {"index": 135, "value": "last-name", "description": ""},
            {"index": 136, "value": "date-of-birth", "description": ""},
            {"index": 137, "value": "gender", "description": ""},
            {"index": 138, "value": "passport-number", "description": ""},
            {"index": 139, "value": "passport-country", "description": ""},
            {"index": 140, "value": "passport-expiration", "description": ""},
            {"index": 141, "value": "redress-number", "description": ""},
            {"index": 142, "value": "nationality", "description": ""},
            {"index": 143, "value": "visa-number", "description": ""},
            {"index": 144, "value": "issue-date-of-the-visa", "description": ""},
            {"index": 145, "value": "primary-residence", "description": ""},
            {"index": 146, "value": "country-of-residence", "description": ""},
            {"index": 147, "value": "special-service-request", "description": ""},
            {"index": 148, "value": "frequent-flyer-number", "description": ""},
            {"index": 149, "value": "travel-details", "description": ""},
            {"index": 150, "value": "payments-details", "description": ""},
            {
                "index": 151,
                "value": "place-port-of-original-embarkation",
                "description": "",
            },
            {
                "index": 152,
                "value": "passenger-name-record-locator-number",
                "description": "",
            },
            {"index": 153, "value": "mobile-application-id", "description": ""},
            {"index": 154, "value": "chrome-extension-id", "description": ""},
            {"index": 155, "value": "cortex", "description": ""},
            {"index": 156, "value": "boolean", "description": ""},
            {"index": 157, "value": "anonymised", "description": ""},
        ],
    },
    {
        "name": "MISP Attribute Distribution",
        "description": "Combo box for MISP attribute type",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Your organisation only", "description": ""},
            {"index": 1, "value": "This community only", "description": ""},
            {"index": 2, "value": "Connected communities", "description": ""},
            {"index": 3, "value": "All communities", "description": ""},
            {"index": 4, "value": "Inherit event", "description": ""},
        ],
    },
    {
        "name": "NIS Sectors",
        "description": "Combo box for NIS sectors",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Energy", "description": ""},
            {"index": 1, "value": "Energy / Electricity", "description": ""},
            {"index": 2, "value": "Energy / Oil", "description": ""},
            {"index": 3, "value": "Energy / Gas", "description": ""},
            {"index": 4, "value": "Transport", "description": ""},
            {"index": 5, "value": "Transport / Air", "description": ""},
            {"index": 6, "value": "Transport / Rail", "description": ""},
            {"index": 7, "value": "Transport / Water", "description": ""},
            {"index": 8, "value": "Transport / Road", "description": ""},
            {"index": 9, "value": "Banking", "description": ""},
            {"index": 10, "value": "Financial market infrastructures", "description": ""},
            {"index": 11, "value": "Health", "description": ""},
            {"index": 12, "value": "Drinking water supply and distribution", "description": ""},
            {"index": 13, "value": "Digital Infrastructure", "description": ""},
            {"index": 14, "value": "public administration", "description": ""},
            {"index": 15, "value": "postal and courier services", "description": ""},
            {"index": 16, "value": "waste management", "description": ""},
            {"index": 17, "value": "food", "description": ""},
            {"index": 18, "value": "processing/manufacturing industry", "description": ""},
            {"index": 19, "value": "Digital service providers", "description": ""},
            {"index": 20, "value": "Research", "description": ""},
            {"index": 21, "value": "Other", "description": ""},
            {"index": 22, "value": "Unknown", "description": ""},
        ],
    },
    {
        "name": "Disinfo type",
        "description": "Types of disinformation",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Satire or parody", "description": "Presenting humorous but false stores as if they are true"},
            {"index": 1, "value": "False connection", "description": "Headlines, visuals or captions don't support the content"},
            {
                "index": 2,
                "value": "Misleading content",
                "description": "Misleading use of information to frame an issue or individual",
            },
            {
                "index": 3,
                "value": "False context",
                "description": "Genuine content is shared with false contextual, e.g. images taken out of context",
            },
            {
                "index": 4,
                "value": "Imposter content",
                "description": "Genuine sources, e.g. news outlets or government agencies, are impersonated",
            },
            {
                "index": 5,
                "value": "Fabricated content",
                "description": "Content is made up and 100% false; designed to deceive and do harm",
            },
            {
                "index": 6,
                "value": "Manipulated content",
                "description": "Genuine information manipulated to deceive, e.g. deepfakes",
            },
            {"index": 7, "value": "Ukraine", "description": "Disinformation about war in Ukraine"},
            {"index": 8, "value": "COVID", "description": "Disinformation about COVID-19"},
            {"index": 9, "value": "Cybesecurity", "description": "Disinformation about Cybesecurity"},
            {"index": 10, "value": "Electronic signature", "description": "Electronic signature"},
            {"index": 11, "value": "Classified information", "description": "Classified information"},
        ],
    },
    {
        "name": "Source Reliability",
        "description": "Source Reliability",
        "type": "RADIO",
        "attribute_enums": [
            {"index": 0, "value": "Completely reliable", "description": ""},
            {"index": 1, "value": "Usually reliable", "description": ""},
            {"index": 2, "value": "Fairly reliable", "description": ""},
            {"index": 3, "value": "Not usually reliable", "description": ""},
            {"index": 4, "value": "Unreliable", "description": ""},
            {"index": 5, "value": "Reliability cannot be judged", "description": ""},
        ],
    },
    {
        "name": "Information Credibility",
        "description": "Information Credibility",
        "type": "RADIO",
        "attribute_enums": [
            {"index": 0, "value": "Confirmed by other sources", "description": ""},
            {"index": 1, "value": "Probably True", "description": ""},
            {"index": 2, "value": "Possibly True", "description": ""},
            {"index": 3, "value": "Doubtful", "description": ""},
            {"index": 4, "value": "Improbable", "description": ""},
            {"index": 5, "value": "Truth cannot be judged", "description": ""},
        ],
    },
]
