workers = [
    {
        "name": "RSS Collector",
        "description": "Collector for gathering data from RSS feeds",
        "parameters": [
            {"parameter": "FEED_URL", "rules": "required"},
            {"parameter": "USER_AGENT"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "ADDITIONAL_HEADERS", "rules": "json"},
            {"parameter": "CONTENT_LOCATION"},
            {"parameter": "XPATH"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
            {"parameter": "DIGEST_SPLITTING", "type": "switch"},
            {
                "parameter": "DIGEST_SPLITTING_LIMIT",
                "type": "number",
                "rules": "digest_splitting_limit",
            },
            {"parameter": "BROWSER_MODE", "type": "switch"},
        ],
        "type": "RSS_COLLECTOR",
    },
    {
        "name": "Simple Web Collector",
        "description": "Collector for gathering data from a web site via python requests",
        "parameters": [
            {"parameter": "WEB_URL", "rules": "required"},
            {"parameter": "USER_AGENT"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "ADDITIONAL_HEADERS"},
            {"parameter": "XPATH"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
            {"parameter": "DIGEST_SPLITTING", "type": "switch"},
            {
                "parameter": "DIGEST_SPLITTING_LIMIT",
                "type": "number",
                "rules": "digest_splitting_limit",
            },
            {"parameter": "BROWSER_MODE", "type": "switch"},
        ],
        "type": "SIMPLE_WEB_COLLECTOR",
    },
    {
        "name": "Manual",
        "description": "Manual source for creating news items via UI",
        "parameters": [
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
        ],
        "type": "MANUAL_COLLECTOR",
    },
    {
        "description": "Collector for gathering data from Request Tracker",
        "name": "RT Collector",
        "parameters": [
            {"parameter": "BASE_URL", "rules": "required"},
            {"parameter": "USER_AGENT"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "ADDITIONAL_HEADERS"},
            {"parameter": "RT_TOKEN", "rules": "required"},
            {"parameter": "SEARCH_QUERY"},
            {"parameter": "FIELDS_TO_INCLUDE"},
            {"parameter": "ADDITIONAL_HEADERS"},
            {"parameter": "TLP_LEVEL", "rules": "tlp"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "type": "RT_COLLECTOR",
    },
    {
        "type": "ANALYST_BOT",
        "name": "Analyst Bot",
        "parameters": [
            {"parameter": "REGULAR_EXPRESSION"},
            {"parameter": "ATTRIBUTE_NAME"},
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for news items analysis",
    },
    {
        "type": "GROUPING_BOT",
        "name": "Grouping Bot",
        "parameters": [
            {"parameter": "REGULAR_EXPRESSION"},
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for grouping news items into stories",
    },
    {
        "type": "NLP_BOT",
        "name": "NLP Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "BOT_API_KEY"},
            {"parameter": "BOT_ENDPOINT", "value": "http://nlp_bot:8000"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for naturale language processing of news items",
    },
    {
        "type": "IOC_BOT",
        "name": "IOC Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for extracting indicators of compromise from news items",
    },
    {
        "type": "TAGGING_BOT",
        "name": "Tagging Bot",
        "parameters": [
            {"parameter": "KEYWORDS"},
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for tagging news items",
    },
    {
        "type": "STORY_BOT",
        "name": "Story Clustering Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER", "value": "range=week"},
            {"parameter": "BOT_API_KEY"},
            {"parameter": "BOT_ENDPOINT", "value": "http://story_bot:8000"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for Story Clustering",
    },
    {
        "type": "SUMMARY_BOT",
        "name": "Summary generation Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "BOT_API_KEY"},
            {"parameter": "BOT_ENDPOINT", "value": "http://summary_bot:8000"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for summarizing stories",
    },
    {
        "type": "WORDLIST_BOT",
        "name": "Wordlist Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "TAGGING_WORDLISTS", "type": "table"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for tagging news items by wordlist",
    },
    {
        "type": "SENTIMENT_ANALYSIS_BOT",
        "name": "Sentiment Analysis Bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "BOT_API_KEY"},
            {"parameter": "BOT_ENDPOINT", "value": "http://sentiment_analysis_bot:8000"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for analyzing sentiment of news items",
    },
    {
        "type": "CYBERSEC_CLASSIFIER_BOT",
        "name": "Cybersecurity classification bot",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "BOT_API_KEY"},
            {"parameter": "BOT_ENDPOINT", "value": "http://cybersec_classifier_bot:8000"},
            {"parameter": "CLASSIFICATION_THRESHOLD", "value": "0.65"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
        "description": "Bot for classifying news items into cybersecurity/non-cybersecurity related",
    },
    {
        "type": "PDF_PRESENTER",
        "description": "Presenter for generating PDF documents",
        "parameters": [{"parameter": "TEMPLATE_PATH", "rules": "required"}],
        "name": "PDF Presenter",
    },
    {
        "type": "HTML_PRESENTER",
        "name": "HTML Presenter",
        "description": "Presenter for generating html documents",
        "parameters": [{"parameter": "TEMPLATE_PATH", "rules": "required"}],
    },
    {
        "type": "TEXT_PRESENTER",
        "name": "TEXT Presenter",
        "description": "Presenter for generating text documents",
        "parameters": [{"parameter": "TEMPLATE_PATH", "rules": "required"}],
    },
    {
        "type": "JSON_PRESENTER",
        "name": "JSON Presenter",
        "description": "Presenter for generating json documents",
        "parameters": [{"parameter": "TEMPLATE_PATH", "rules": "required"}],
    },
    {
        "type": "FTP_PUBLISHER",
        "name": "FTP Publisher",
        "description": "Publisher for publishing to FTP server",
        "parameters": [{"parameter": "FTP_URL", "rules": "required"}],
    },
    {
        "type": "SFTP_PUBLISHER",
        "name": "SFTP Publisher",
        "description": "Publisher for publishing to SFTP server",
        "parameters": [{"parameter": "SFTP_URL", "rules": "required"}, {"parameter": "PRIVATE_KEY"}],
    },
    {
        "type": "EMAIL_PUBLISHER",
        "name": "EMAIL Publisher",
        "description": "Publisher for publishing by email",
        "parameters": [
            {"parameter": "SMTP_SERVER_ADDRESS", "rules": "required"},
            {"parameter": "SMTP_SERVER_PORT", "type": "number"},
            {"parameter": "SERVER_TLS", "type": "switch"},
            {"parameter": "EMAIL_USERNAME"},
            {"parameter": "EMAIL_PASSWORD"},
            {"parameter": "EMAIL_SENDER", "rules": "required,email"},
            {"parameter": "EMAIL_RECIPIENT", "rules": "required,email"},
            {"parameter": "EMAIL_SUBJECT"},
        ],
    },
    {
        "type": "WORDPRESS_PUBLISHER",
        "name": "Wordpress Publisher",
        "description": "Publisher for publishing on Wordpress webpage",
        "parameters": [{"parameter": "WP_URL"}, {"parameter": "WP_USER"}, {"parameter": "WP_PYTHON_APP_SECRET"}],
    },
    {
        "type": "MISP_PUBLISHER",
        "name": "MISP Publisher",
        "description": "Publisher for publishing in MISP",
        "parameters": [{"parameter": "MISP_URL"}, {"parameter": "MISP_API_KEY"}],
    },
    {
        "type": "MISP_CONNECTOR",
        "name": "MISP Connector",
        "description": "Connetor for MISP",
        "parameters": [
            {"parameter": "URL", "rules": "required"},
            {"parameter": "API_KEY", "rules": "required"},
            {"parameter": "ORGANISATION_ID", "rules": "required"},
            {"parameter": "SSL_CHECK", "type": "switch"},
            {"parameter": "REQUEST_TIMEOUT", "type": "number"},
            {"parameter": "USER_AGENT"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "ADDITIONAL_HEADERS", "rules": "json"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
            {"parameter": "SHARING_GROUP_ID"},
            {"parameter": "DISTRIBUTION"},
        ],
    },
    {
        "type": "MISP_COLLECTOR",
        "name": "MISP Collector",
        "description": "Colletor for MISP",
        "parameters": [
            {"parameter": "URL", "rules": "required"},
            {"parameter": "API_KEY", "rules": "required"},
            {"parameter": "ORGANISATION_ID", "rules": "required"},
            {"parameter": "SSL_CHECK", "type": "switch"},
            {"parameter": "REQUEST_TIMEOUT", "type": "number"},
            {"parameter": "USER_AGENT"},
            {"parameter": "PROXY_SERVER"},
            {"parameter": "ADDITIONAL_HEADERS", "rules": "json"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
            {"parameter": "SHARING_GROUP_ID"},
        ],
    },
]


bots = [
    {
        "name": "Wordlist Bot",
        "description": "Bot for tagging news items by wordlist",
        "type": "WORDLIST_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
    },
    {
        "name": "IOC Bot",
        "description": "Bot for Tagging news items",
        "type": "IOC_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
    },
    {
        "name": "NLP Tagging Bot",
        "description": "Bot for Tagging Items via NLP",
        "type": "NLP_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch", "value": "true"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
    },
    {
        "name": "Story Bot",
        "description": "Bot for story clustering",
        "type": "STORY_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER", "value": "limit=666"},
        ],
    },
    {
        "name": "Sentiment Analysis Bot",
        "description": "Bot for analyzing sentiment of news items",
        "type": "SENTIMENT_ANALYSIS_BOT",
        "parameters": [
            {"parameter": "ITEM_FILTER"},
            {"parameter": "RUN_AFTER_COLLECTOR", "type": "switch"},
            {"parameter": "REFRESH_INTERVAL", "type": "cron_interval"},
        ],
    },
    {
        "name": "Summary Bot",
        "description": "Bot for summarizing stories",
        "type": "SUMMARY_BOT",
    },
    {
        "name": "Cybersecurity Classifier Bot",
        "description": "Bot for classifying news items into cybersecurity/non-cybersecurity related",
        "type": "CYBERSEC_CLASSIFIER_BOT",
    },
]

# ADD NEW REPORT TYPE AT THE END OF THE LIST.
# At the moment, the report types are implicitly referenced by the product types.
report_types = [
    {
        "title": "OSINT Report",
        "description": "Example OSINT Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Summary",
                "description": "Summary",
                "index": 0,
                "attribute_group_items": [
                    {"title": "Summary", "description": "Summary", "index": 0, "attribute": "Text Area"},
                    {"title": "Sector trends", "description": "Sector trends", "index": 1, "attribute": "Text Area"},
                    {"title": "Vulnerabilities trends", "description": "Vulnerabilities trends", "index": 2, "attribute": "Text Area"},
                    {"title": "Ransomware trends", "description": "Ransomware trends", "index": 3, "attribute": "Text Area"},
                    {"title": "Date published", "description": "Date published", "index": 4, "attribute": "Date"},
                    {"title": "Threat level", "description": "Threat level", "index": 5, "attribute": "MISP Event Threat Level"},
                    {"title": "TLP", "description": "Traffic Light Protocol", "index": 6, "attribute": "TLP"},
                ],
            },
            {
                "title": "Ransomware",
                "description": "Ransomware",
                "index": 1,
                "attribute_group_items": [
                    {"title": "Ransomware", "description": "Ransomware", "index": 0, "attribute": "Text"},
                    {"title": "Actor", "description": "Actor", "index": 1, "attribute": "Text"},
                    {"title": "Sector", "description": "Sector", "index": 2, "attribute": "NIS Sectors"},
                    {"title": "Comment", "description": "Comment", "index": 3, "attribute": "Text Area"},
                ],
            },
        ],
    },
    {
        "title": "Disinformation",
        "description": "Example Disinformation Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Summary",
                "description": "Summary",
                "index": 0,
                "attribute_group_items": [
                    {"title": "Title", "description": "Disinformation campaign", "index": 0, "attribute": "Text"},
                    {"title": "Quote", "description": "Quote", "index": 1, "attribute": "Text Area"},
                    {"title": "Reach", "description": "Exposed people", "index": 2, "attribute": "Number"},
                    {"title": "Date started", "description": "Campaign started", "index": 3, "attribute": "Date"},
                    {"title": "Proof", "description": "Screenshots, ...", "index": 4, "attribute": "Attachment"},
                ],
            },
            {
                "title": "Ransomware",
                "description": "Ransomware",
                "index": 1,
                "attribute_group_items": [
                    {"title": "Ransomware", "description": "Ransomware", "index": 0, "attribute": "Text"},
                    {"title": "Actor", "description": "Actor", "index": 1, "attribute": "Text"},
                    {"title": "Sector", "description": "Sector", "index": 2, "attribute": "NIS Sectors"},
                    {"title": "Comment", "description": "Comment", "index": 3, "attribute": "Text Area"},
                ],
            },
        ],
    },
    {
        "title": "Vulnerability Report",
        "description": "Example Vulnerability Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Vulnerability",
                "description": "Vulnerability",
                "index": 0,
                "attribute_group_items": [
                    {
                        "title": "CVSS",
                        "description": "Common Vulnerability Scoring System",
                        "index": 0,
                        "attribute": "CVSS",
                    },
                    {
                        "title": "TLP",
                        "description": "Traffic Light Protocol",
                        "index": 1,
                        "attribute": "TLP",
                    },
                    {
                        "title": "Confidentiality",
                        "description": "Confidentiality",
                        "index": 2,
                        "attribute": "Confidentiality",
                    },
                    {
                        "title": "Description",
                        "description": "Description",
                        "index": 3,
                        "attribute": "Text Area",
                    },
                    {
                        "title": "Exposure Date",
                        "description": "Exposure Date",
                        "index": 4,
                        "attribute": "Date",
                    },
                    {
                        "title": "Update Date",
                        "description": "Update Date",
                        "index": 5,
                        "attribute": "Date",
                    },
                    {
                        "title": "CVE",
                        "description": "CVE",
                        "index": 6,
                        "attribute": "CVE",
                    },
                    {
                        "title": "Impact",
                        "description": "Impact",
                        "index": 7,
                        "attribute": "Impact",
                    },
                    {
                        "title": "Links",
                        "description": "Links",
                        "index": 8,
                        "attribute": "Text",
                    },
                ],
            },
            {
                "title": "Identify and Act",
                "description": "Identify and Act",
                "index": 1,
                "attribute_group_items": [
                    {
                        "title": "Affected Systems",
                        "description": "Affected Systems",
                        "index": 0,
                        "attribute": "CPE",
                    },
                    {
                        "title": "IOC",
                        "description": "IOC",
                        "index": 1,
                        "attribute": "Text",
                    },
                    {
                        "title": "Recommendations",
                        "description": "Recommendations",
                        "index": 2,
                        "attribute": "Text Area",
                    },
                ],
            },
        ],
    },
    {
        "title": "CERT Report",
        "description": "Example CERT Report provided by Taranis AI",
        "attribute_groups": [
            {
                "title": "Data",
                "description": "Data",
                "index": 0,
                "attribute_group_items": [
                    {"title": "date", "description": "Date", "index": 0, "attribute": "Text"},
                    {"title": "timeframe", "description": "Timeframe", "index": 1, "attribute": "Text"},
                    {"title": "handler", "description": "Handler", "index": 2, "attribute": "Text"},
                    {"title": "co_handler", "description": "CO-Handler", "index": 3, "attribute": "Text"},
                    {"title": "news", "description": "News", "index": 4, "attribute": "Story", "required": True},
                    {"title": "vulnerabilities", "description": "Vulnerabilities", "index": 5, "attribute": "Story", "required": True},
                ],
            }
        ],
    },
]


product_types = [
    {
        "title": "Default PDF Presenter",
        "description": "Default PDF Presenter",
        "type": "PDF_PRESENTER",
        "parameters": [
            {"parameter": "TEMPLATE_PATH", "value": "pdf_template.html"},
        ],
        "report_types": [1, 2, 3, 4],
    },
    {
        "title": "Default TEXT Presenter",
        "description": "Default TEXT Presenter",
        "type": "TEXT_PRESENTER",
        "parameters": [
            {"parameter": "TEMPLATE_PATH", "value": "text_template.txt"},
        ],
        "report_types": [1, 2, 3, 4],
    },
    {
        "title": "CERT Daily Report",
        "description": "cert.at Daily Report HTML",
        "type": "HTML_PRESENTER",
        "parameters": [
            {"parameter": "TEMPLATE_PATH", "value": "cert_at_daily_report.html"},
        ],
        "report_types": [4],
    },
]

permissions: list[dict] = [
    {"id": "ADMIN_OPERATIONS", "name": "Admin operations", "description": "Admin operations"},
    {"id": "ASSESS_ACCESS", "name": "Assess access", "description": "Access to Assess module"},
    {"id": "ASSESS_CREATE", "name": "Assess create", "description": "Create news item"},
    {"id": "ASSESS_UPDATE", "name": "Assess update", "description": "Update news item"},
    {"id": "ASSESS_DELETE", "name": "Assess delete", "description": "Delete news item"},
    {"id": "ANALYZE_ACCESS", "name": "Analyze access", "description": "Access to Analyze module"},
    {"id": "ANALYZE_CREATE", "name": "Analyze create", "description": "Create report item"},
    {"id": "ANALYZE_UPDATE", "name": "Analyze update", "description": "Update report item"},
    {"id": "ANALYZE_DELETE", "name": "Analyze delete", "description": "Delete report item"},
    {"id": "BOT_EXECUTE", "name": "Bot execute", "description": "Execute bot"},
    {"id": "PUBLISH_ACCESS", "name": "Publish access", "description": "Access to publish module"},
    {"id": "PUBLISH_CREATE", "name": "Publish create", "description": "Create product"},
    {"id": "PUBLISH_UPDATE", "name": "Publish update", "description": "Update product"},
    {"id": "PUBLISH_DELETE", "name": "Publish delete", "description": "Delete product"},
    {"id": "PUBLISH_PRODUCT", "name": "Publish product", "description": "Publish product"},
    {"id": "CONFIG_ACCESS", "name": "Configuration access", "description": "Access uncategorized configs"},
    {"id": "CONFIG_ORGANIZATION_ACCESS", "name": "Config organizations access", "description": "Access to attributes"},
    {"id": "CONFIG_ORGANIZATION_CREATE", "name": "Config organization create", "description": "Create organization"},
    {"id": "CONFIG_ORGANIZATION_UPDATE", "name": "Config organization update", "description": "Update organization"},
    {"id": "CONFIG_ORGANIZATION_DELETE", "name": "Config organization delete", "description": "Delete organization"},
    {"id": "CONFIG_USER_ACCESS", "name": "Config users access", "description": "Access to users"},
    {"id": "CONFIG_USER_CREATE", "name": "Config user create", "description": "Create user"},
    {"id": "CONFIG_USER_UPDATE", "name": "Config user update", "description": "Update user"},
    {"id": "CONFIG_USER_DELETE", "name": "Config user delete", "description": "Delete user"},
    {"id": "CONFIG_ROLE_ACCESS", "name": "Config roles access", "description": "Access to roles"},
    {"id": "CONFIG_ROLE_CREATE", "name": "Config role create", "description": "Create role"},
    {"id": "CONFIG_ROLE_UPDATE", "name": "Config role update", "description": "Update role"},
    {"id": "CONFIG_ROLE_DELETE", "name": "Config role delete", "description": "Delete role"},
    {"id": "CONFIG_ACL_ACCESS", "name": "Config acls access", "description": "Access to acls"},
    {"id": "CONFIG_ACL_CREATE", "name": "Config acl create", "description": "Create acl"},
    {"id": "CONFIG_ACL_UPDATE", "name": "Config acl update", "description": "Update acl"},
    {"id": "CONFIG_ACL_DELETE", "name": "Config acl delete", "description": "Delete acl"},
    {"id": "CONFIG_PRODUCT_TYPE_ACCESS", "name": "Config product types access", "description": "Access to product types"},
    {"id": "CONFIG_PRODUCT_TYPE_CREATE", "name": "Config product type create", "description": "Create product type"},
    {"id": "CONFIG_PRODUCT_TYPE_UPDATE", "name": "Config product type update", "description": "Update product type"},
    {"id": "CONFIG_PRODUCT_TYPE_DELETE", "name": "Config product type delete", "description": "Delete product type"},
    {"id": "CONFIG_ATTRIBUTE_ACCESS", "name": "Config attributes access", "description": "Access to attributes"},
    {"id": "CONFIG_ATTRIBUTE_CREATE", "name": "Config attribute create", "description": "Create attribute"},
    {"id": "CONFIG_ATTRIBUTE_UPDATE", "name": "Config attribute update", "description": "Update attribute"},
    {"id": "CONFIG_ATTRIBUTE_DELETE", "name": "Config attribute delete", "description": "Delete attribute"},
    {"id": "CONFIG_REPORT_TYPE_ACCESS", "name": "Config report types access", "description": "Access to report types"},
    {"id": "CONFIG_REPORT_TYPE_CREATE", "name": "Config report type create", "description": "Create report type"},
    {"id": "CONFIG_REPORT_TYPE_UPDATE", "name": "Config report type update", "description": "Update report type"},
    {"id": "CONFIG_REPORT_TYPE_DELETE", "name": "Config report type delete", "description": "Delete report type"},
    {"id": "CONFIG_WORD_LIST_ACCESS", "name": "Config word lists access", "description": "Access to word lists"},
    {"id": "CONFIG_WORD_LIST_CREATE", "name": "Config word list create", "description": "Create word list"},
    {"id": "CONFIG_WORD_LIST_UPDATE", "name": "Config word list update", "description": "Update word list"},
    {"id": "CONFIG_WORD_LIST_DELETE", "name": "Config word list delete", "description": "Delete word list"},
    {"id": "CONFIG_OSINT_SOURCE_ACCESS", "name": "Config OSINT source access", "description": "Access to OSINT sources"},
    {"id": "CONFIG_OSINT_SOURCE_CREATE", "name": "Config OSINT source create", "description": "Create OSINT source"},
    {"id": "CONFIG_OSINT_SOURCE_UPDATE", "name": "Config OSINT source update", "description": "Update OSINT source"},
    {"id": "CONFIG_OSINT_SOURCE_DELETE", "name": "Config OSINT source delete", "description": "Delete OSINT source"},
    {"id": "CONFIG_OSINT_SOURCE_GROUP_ACCESS", "name": "Config Sourcegroup access", "description": "Access to OSINT-Sourcegroups"},
    {"id": "CONFIG_OSINT_SOURCE_GROUP_CREATE", "name": "Config OSINT source group create", "description": "Create OSINT-Sourcegroup"},
    {"id": "CONFIG_OSINT_SOURCE_GROUP_UPDATE", "name": "Config OSINT source group update", "description": "Update OSINT-Sourcegroup"},
    {"id": "CONFIG_OSINT_SOURCE_GROUP_DELETE", "name": "Config OSINT source group delete", "description": "Delete OSINT-Sourcegroup"},
    {"id": "CONFIG_BOT_ACCESS", "name": "Config bots access", "description": "Access to bots configuration"},
    {"id": "CONFIG_BOT_CREATE", "name": "Config bot create", "description": "Create bot configuration"},
    {"id": "CONFIG_BOT_UPDATE", "name": "Config bot update", "description": "Update bot configuration"},
    {"id": "CONFIG_BOT_DELETE", "name": "Config bot delete", "description": "Delete bot configuration"},
    {"id": "CONFIG_PUBLISHER_ACCESS", "name": "Config publisher presets access", "description": "Access to publisher presets"},
    {"id": "CONFIG_PUBLISHER_CREATE", "name": "Config publisher preset create", "description": "Create publisher preset"},
    {"id": "CONFIG_PUBLISHER_UPDATE", "name": "Config publisher preset update", "description": "Update publisher preset"},
    {"id": "CONFIG_PUBLISHER_DELETE", "name": "Config publisher preset delete", "description": "Delete publisher preset"},
    {"id": "ASSETS_ACCESS", "name": "Assets access", "description": "Access to Assets"},
    {"id": "ASSETS_CREATE", "name": "My Assets create", "description": "Creation of new Assets"},
    {"id": "ASSETS_CONFIG", "name": "My Assets config", "description": "Configuration of access and groups"},
    {"id": "CONFIG_WORKER_ACCESS", "name": "Access to workers", "description": "Access to workers configuration"},
    {"id": "CONFIG_API_ACCESS", "name": "Config API access", "description": "Access to API configuration"},
    {"id": "CONFIG_CONNECTOR_ACCESS", "name": "Config connector access", "description": "Access to connector configuration"},
    {"id": "CONFIG_CONNECTOR_CREATE", "name": "Config connector create", "description": "Create to connector configuration"},
    {"id": "CONFIG_CONNECTOR_UPDATE", "name": "Config connector update", "description": "Update to connector configuration"},
    {"id": "CONFIG_CONNECTOR_DELETE", "name": "Config connector delete", "description": "Delete to connector configuration"},
    {"id": "CONNECTOR_USER_ACCESS", "name": "Connector user access", "description": "Access to connector management"},
]


attrs_with_enum = [
    {
        "name": "Confidentiality",
        "description": "Radio box for confidentiality level",
        "type": "RADIO",
        "attribute_enums": [
            {"index": 0, "value": "UNRESTRICTED", "description": ""},
            {"index": 1, "value": "CLASSIFIED", "description": ""},
            {"index": 2, "value": "CONFIDENTIAL", "description": ""},
            {"index": 3, "value": "SECRET", "description": ""},
            {"index": 4, "value": "TOP SECRET", "description": ""},
        ],
    },
    {
        "name": "Impact",
        "description": "Combo box for impact level",
        "type": "ENUM",
        "attribute_enums": [
            {
                "index": 0,
                "value": "Malicious code execution affecting CIA of the system",
                "description": "",
            },
            {"index": 1, "value": "Malicious code execution", "description": ""},
            {"index": 2, "value": "Denial of service", "description": ""},
            {"index": 3, "value": "Privilege escalation", "description": ""},
            {"index": 4, "value": "Information exposure", "description": ""},
            {
                "index": 5,
                "value": "Unauthorized access to the system",
                "description": "",
            },
            {"index": 6, "value": "Unauthorized change in system", "description": ""},
        ],
    },
    {
        "name": "MISP Event Distribution",
        "description": "Combo box for MISP event distribution",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Your organisation only", "description": ""},
            {"index": 1, "value": "This community only", "description": ""},
            {"index": 2, "value": "Connected communities", "description": ""},
            {"index": 3, "value": "All communities", "description": ""},
        ],
    },
    {
        "name": "MISP Event Threat Level",
        "description": "Combo box for MISP event threat level",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "High", "description": ""},
            {"index": 1, "value": "Medium", "description": ""},
            {"index": 2, "value": "Low", "description": ""},
            {"index": 3, "value": "Undefined", "description": ""},
        ],
    },
    {
        "name": "MISP Event Analysis",
        "description": "Combo box for MISP event analysis",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Initial", "description": ""},
            {"index": 1, "value": "Ongoing", "description": ""},
            {"index": 2, "value": "Completed", "description": ""},
        ],
    },
    {
        "name": "MISP Attribute Category",
        "description": "Combo box for MISP attribute category",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Internal reference", "description": ""},
            {"index": 1, "value": "Targeting data", "description": ""},
            {"index": 2, "value": "Antivirus detection", "description": ""},
            {"index": 3, "value": "Payload delivery", "description": ""},
            {"index": 4, "value": "Artifacts dropped", "description": ""},
            {"index": 5, "value": "Payload installation", "description": ""},
            {"index": 6, "value": "Persistence mechanism", "description": ""},
            {"index": 7, "value": "Network activity", "description": ""},
            {"index": 8, "value": "Payload type", "description": ""},
            {"index": 9, "value": "Attribution", "description": ""},
            {"index": 10, "value": "External analysis", "description": ""},
            {"index": 11, "value": "Financial fraud", "description": ""},
            {"index": 12, "value": "Support Tool", "description": ""},
            {"index": 13, "value": "Social network", "description": ""},
            {"index": 14, "value": "Person", "description": ""},
            {"index": 15, "value": "Other", "description": ""},
        ],
    },
    {
        "name": "MISP Attribute Type",
        "description": "Combo box for MISP attribute type",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "md5", "description": ""},
            {"index": 1, "value": "sha1", "description": ""},
            {"index": 2, "value": "sha256", "description": ""},
            {"index": 3, "value": "filename", "description": ""},
            {"index": 4, "value": "pbd", "description": ""},
            {"index": 5, "value": "filename|md5", "description": ""},
            {"index": 6, "value": "filename|sha1", "description": ""},
            {"index": 7, "value": "filename|sha256", "description": ""},
            {"index": 8, "value": "ip-src", "description": ""},
            {"index": 9, "value": "ip-dst", "description": ""},
            {"index": 10, "value": "hostname", "description": ""},
            {"index": 11, "value": "domain", "description": ""},
            {"index": 12, "value": "domain|ip", "description": ""},
            {"index": 13, "value": "email-src", "description": ""},
            {"index": 14, "value": "eppn", "description": ""},
            {"index": 15, "value": "email-dst", "description": ""},
            {"index": 16, "value": "email-subject", "description": ""},
            {"index": 17, "value": "email-attachment", "description": ""},
            {"index": 18, "value": "email-body", "description": ""},
            {"index": 19, "value": "float", "description": ""},
            {"index": 20, "value": "url", "description": ""},
            {"index": 21, "value": "http-method", "description": ""},
            {"index": 22, "value": "user-agent", "description": ""},
            {"index": 23, "value": "ja3-fingerprint-md5", "description": ""},
            {"index": 24, "value": "hassh-md5", "description": ""},
            {"index": 25, "value": "hasshserver-md5", "description": ""},
            {"index": 26, "value": "reg-key", "description": ""},
            {"index": 27, "value": "regkey|value", "description": ""},
            {"index": 28, "value": "AS", "description": ""},
            {"index": 29, "value": "snort", "description": ""},
            {"index": 30, "value": "bro", "description": ""},
            {"index": 31, "value": "zeek", "description": ""},
            {"index": 32, "value": "community-id", "description": ""},
            {"index": 33, "value": "pattern-in-traffic", "description": ""},
            {"index": 34, "value": "pattern-in-memory", "description": ""},
            {"index": 35, "value": "yara", "description": ""},
            {"index": 36, "value": "stix2-pattern", "description": ""},
            {"index": 37, "value": "sigma", "description": ""},
            {"index": 38, "value": "gene", "description": ""},
            {"index": 39, "value": "kusto-query", "description": ""},
            {"index": 40, "value": "mime-type", "description": ""},
            {"index": 41, "value": "identity-card-number", "description": ""},
            {"index": 42, "value": "cookie", "description": ""},
            {"index": 43, "value": "vulnerability", "description": ""},
            {"index": 44, "value": "weakness", "description": ""},
            {"index": 45, "value": "link", "description": ""},
            {"index": 46, "value": "comment", "description": ""},
            {"index": 47, "value": "text", "description": ""},
            {"index": 48, "value": "hex", "description": ""},
            {"index": 49, "value": "other", "description": ""},
            {"index": 50, "value": "named pipe", "description": ""},
            {"index": 51, "value": "mutex", "description": ""},
            {"index": 52, "value": "target-user", "description": ""},
            {"index": 53, "value": "target-email", "description": ""},
            {"index": 54, "value": "target-machine", "description": ""},
            {"index": 55, "value": "target-org", "description": ""},
            {"index": 56, "value": "target-location", "description": ""},
            {"index": 57, "value": "target-external", "description": ""},
            {"index": 58, "value": "btc", "description": ""},
            {"index": 59, "value": "dash", "description": ""},
            {"index": 60, "value": "xmr", "description": ""},
            {"index": 61, "value": "iban", "description": ""},
            {"index": 62, "value": "bic", "description": ""},
            {"index": 63, "value": "bank-account-nr", "description": ""},
            {"index": 64, "value": "aba-rtn", "description": ""},
            {"index": 65, "value": "bin", "description": ""},
            {"index": 66, "value": "cc-number", "description": ""},
            {"index": 67, "value": "prtn", "description": ""},
            {"index": 68, "value": "phone-number", "description": ""},
            {"index": 69, "value": "threat-actor", "description": ""},
            {"index": 70, "value": "campaign-name", "description": ""},
            {"index": 71, "value": "campaign-id", "description": ""},
            {"index": 72, "value": "malware-type", "description": ""},
            {"index": 73, "value": "uri", "description": ""},
            {"index": 74, "value": "authentihash", "description": ""},
            {"index": 75, "value": "ssdeep", "description": ""},
            {"index": 76, "value": "implash", "description": ""},
            {"index": 77, "value": "pahash", "description": ""},
            {"index": 78, "value": "impfuzzy", "description": ""},
            {"index": 79, "value": "sha224", "description": ""},
            {"index": 80, "value": "sha384", "description": ""},
            {"index": 81, "value": "sha512", "description": ""},
            {"index": 82, "value": "sha512/224", "description": ""},
            {"index": 83, "value": "sha512/256", "description": ""},
            {"index": 84, "value": "tlsh", "description": ""},
            {"index": 85, "value": "cdhash", "description": ""},
            {"index": 86, "value": "filename|authentihash", "description": ""},
            {"index": 87, "value": "filename|ssdeep", "description": ""},
            {"index": 88, "value": "filename|implash", "description": ""},
            {"index": 89, "value": "filename|impfuzzy", "description": ""},
            {"index": 90, "value": "filename|pehash", "description": ""},
            {"index": 91, "value": "filename|sha224", "description": ""},
            {"index": 92, "value": "filename|sha384", "description": ""},
            {"index": 93, "value": "filename|sha512", "description": ""},
            {"index": 94, "value": "filename|sha512/224", "description": ""},
            {"index": 95, "value": "filename|sha512/256", "description": ""},
            {"index": 96, "value": "filename|tlsh", "description": ""},
            {"index": 97, "value": "windows-scheduled-task", "description": ""},
            {"index": 98, "value": "windows-service-name", "description": ""},
            {"index": 99, "value": "windows-service-displayname", "description": ""},
            {"index": 100, "value": "whois-registrant-email", "description": ""},
            {"index": 101, "value": "whois-registrant-phone", "description": ""},
            {"index": 102, "value": "whois-registrant-name", "description": ""},
            {"index": 103, "value": "whois-registrant-org", "description": ""},
            {"index": 104, "value": "whois-registrar", "description": ""},
            {"index": 105, "value": "whois-creation-date", "description": ""},
            {"index": 106, "value": "x509-fingerprint-sha1", "description": ""},
            {"index": 107, "value": "x509-fingerprint-md5", "description": ""},
            {"index": 108, "value": "x509-fingerprint-sha256", "description": ""},
            {"index": 109, "value": "dns-soa-email", "description": ""},
            {"index": 110, "value": "size-in-bytes", "description": ""},
            {"index": 111, "value": "counter", "description": ""},
            {"index": 112, "value": "datetime", "description": ""},
            {"index": 113, "value": "cpe", "description": ""},
            {"index": 114, "value": "port", "description": ""},
            {"index": 115, "value": "ip-dist|port", "description": ""},
            {"index": 116, "value": "ip-src|port", "description": ""},
            {"index": 117, "value": "hostname|port", "description": ""},
            {"index": 118, "value": "mac-address", "description": ""},
            {"index": 119, "value": "mac-eui-64", "description": ""},
            {"index": 120, "value": "email-dst-display-name", "description": ""},
            {"index": 121, "value": "email-src-display-name", "description": ""},
            {"index": 122, "value": "email-header", "description": ""},
            {"index": 123, "value": "email-reply-to", "description": ""},
            {"index": 124, "value": "email-x-mailer", "description": ""},
            {"index": 125, "value": "email-mime-boundary", "description": ""},
            {"index": 126, "value": "email-thread-index", "description": ""},
            {"index": 127, "value": "email-message-id", "description": ""},
            {"index": 128, "value": "github-username", "description": ""},
            {"index": 129, "value": "github-repository", "description": ""},
            {"index": 130, "value": "githzb-organisation", "description": ""},
            {"index": 131, "value": "jabber-id", "description": ""},
            {"index": 132, "value": "twitter-id", "description": ""},
            {"index": 133, "value": "first-name", "description": ""},
            {"index": 134, "value": "middle-name", "description": ""},
            {"index": 135, "value": "last-name", "description": ""},
            {"index": 136, "value": "date-of-birth", "description": ""},
            {"index": 137, "value": "gender", "description": ""},
            {"index": 138, "value": "passport-number", "description": ""},
            {"index": 139, "value": "passport-country", "description": ""},
            {"index": 140, "value": "passport-expiration", "description": ""},
            {"index": 141, "value": "redress-number", "description": ""},
            {"index": 142, "value": "nationality", "description": ""},
            {"index": 143, "value": "visa-number", "description": ""},
            {"index": 144, "value": "issue-date-of-the-visa", "description": ""},
            {"index": 145, "value": "primary-residence", "description": ""},
            {"index": 146, "value": "country-of-residence", "description": ""},
            {"index": 147, "value": "special-service-request", "description": ""},
            {"index": 148, "value": "frequent-flyer-number", "description": ""},
            {"index": 149, "value": "travel-details", "description": ""},
            {"index": 150, "value": "payments-details", "description": ""},
            {
                "index": 151,
                "value": "place-port-of-original-embarkation",
                "description": "",
            },
            {
                "index": 152,
                "value": "passenger-name-record-locator-number",
                "description": "",
            },
            {"index": 153, "value": "mobile-application-id", "description": ""},
            {"index": 154, "value": "chrome-extension-id", "description": ""},
            {"index": 155, "value": "cortex", "description": ""},
            {"index": 156, "value": "boolean", "description": ""},
            {"index": 157, "value": "anonymised", "description": ""},
        ],
    },
    {
        "name": "MISP Attribute Distribution",
        "description": "Combo box for MISP attribute type",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Your organisation only", "description": ""},
            {"index": 1, "value": "This community only", "description": ""},
            {"index": 2, "value": "Connected communities", "description": ""},
            {"index": 3, "value": "All communities", "description": ""},
            {"index": 4, "value": "Inherit event", "description": ""},
        ],
    },
    {
        "name": "NIS Sectors",
        "description": "Combo box for NIS sectors",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Energy", "description": ""},
            {"index": 1, "value": "Energy / Electricity", "description": ""},
            {"index": 2, "value": "Energy / Oil", "description": ""},
            {"index": 3, "value": "Energy / Gas", "description": ""},
            {"index": 4, "value": "Transport", "description": ""},
            {"index": 5, "value": "Transport / Air", "description": ""},
            {"index": 6, "value": "Transport / Rail", "description": ""},
            {"index": 7, "value": "Transport / Water", "description": ""},
            {"index": 8, "value": "Transport / Road", "description": ""},
            {"index": 9, "value": "Banking", "description": ""},
            {"index": 10, "value": "Financial market infrastructures", "description": ""},
            {"index": 11, "value": "Health", "description": ""},
            {"index": 12, "value": "Drinking water supply and distribution", "description": ""},
            {"index": 13, "value": "Digital Infrastructure", "description": ""},
            {"index": 14, "value": "public administration", "description": ""},
            {"index": 15, "value": "postal and courier services", "description": ""},
            {"index": 16, "value": "waste management", "description": ""},
            {"index": 17, "value": "food", "description": ""},
            {"index": 18, "value": "processing/manufacturing industry", "description": ""},
            {"index": 19, "value": "Digital service providers", "description": ""},
            {"index": 20, "value": "Research", "description": ""},
            {"index": 21, "value": "Other", "description": ""},
            {"index": 22, "value": "Unknown", "description": ""},
        ],
    },
    {
        "name": "Disinfo type",
        "description": "Types of disinformation",
        "type": "ENUM",
        "attribute_enums": [
            {"index": 0, "value": "Satire or parody", "description": "Presenting humorous but false stores as if they are true"},
            {"index": 1, "value": "False connection", "description": "Headlines, visuals or captions don't support the content"},
            {
                "index": 2,
                "value": "Misleading content",
                "description": "Misleading use of information to frame an issue or individual",
            },
            {
                "index": 3,
                "value": "False context",
                "description": "Genuine content is shared with false contextual, e.g. images taken out of context",
            },
            {
                "index": 4,
                "value": "Imposter content",
                "description": "Genuine sources, e.g. news outlets or government agencies, are impersonated",
            },
            {
                "index": 5,
                "value": "Fabricated content",
                "description": "Content is made up and 100% false; designed to deceive and do harm",
            },
            {
                "index": 6,
                "value": "Manipulated content",
                "description": "Genuine information manipulated to deceive, e.g. deepfakes",
            },
            {"index": 7, "value": "Ukraine", "description": "Disinformation about war in Ukraine"},
            {"index": 8, "value": "COVID", "description": "Disinformation about COVID-19"},
            {"index": 9, "value": "Cybesecurity", "description": "Disinformation about Cybesecurity"},
            {"index": 10, "value": "Electronic signature", "description": "Electronic signature"},
            {"index": 11, "value": "Classified information", "description": "Classified information"},
        ],
    },
    {
        "name": "Source Reliability",
        "description": "Source Reliability",
        "type": "RADIO",
        "attribute_enums": [
            {"index": 0, "value": "Completely reliable", "description": ""},
            {"index": 1, "value": "Usually reliable", "description": ""},
            {"index": 2, "value": "Fairly reliable", "description": ""},
            {"index": 3, "value": "Not usually reliable", "description": ""},
            {"index": 4, "value": "Unreliable", "description": ""},
            {"index": 5, "value": "Reliability cannot be judged", "description": ""},
        ],
    },
    {
        "name": "Information Credibility",
        "description": "Information Credibility",
        "type": "RADIO",
        "attribute_enums": [
            {"index": 0, "value": "Confirmed by other sources", "description": ""},
            {"index": 1, "value": "Probably True", "description": ""},
            {"index": 2, "value": "Possibly True", "description": ""},
            {"index": 3, "value": "Doubtful", "description": ""},
            {"index": 4, "value": "Improbable", "description": ""},
            {"index": 5, "value": "Truth cannot be judged", "description": ""},
        ],
    },
]
