misp_connector = {
    "description": "",
    "icon": None,
    "id": "74981521-4ba7-4216-b9ca-ebc00ffec29c",
    "last_attempted": None,
    "last_collected": None,
    "last_error_message": None,
    "name": "test connector",
    "parameters": {
        "ADDITIONAL_HEADERS": "",
        "API_KEY": "test_api_key",
        "DISTRIBUTION": "",
        "ORGANISATION_ID": "1",
        "PROXY_SERVER": "",
        "REFRESH_INTERVAL": "",
        "REQUEST_TIMEOUT": "",
        "SHARING_GROUP_ID": "",
        "SSL_CHECK": "",
        "URL": "https://test.misp.test",
        "USER_AGENT": "",
    },
    "state": -1,
    "type": "misp_connector",
}
